import {MAP_REGIONS,selectMapPrefecture} from './japan-map.mjs?v=052';
import {createAnalytics,context as analyticsContext,analyticsNotice} from './analytics.mjs?v=051';
import {layoutNotes} from './room-layout.mjs?v=051';
import {productLinks,productDisclosure} from './product-links.mjs?v=051';
import {weeklyActions,mobileWeekBar} from './operation-ui.mjs?v=051';
import {recapSelection} from './recap-selection.mjs?v=051';
import {inspectionQuestion,answerInspection,completeComparison,completeCalendar} from './research-activities.mjs?v=051';
import {inspectionScene,comparisonPanel,calendarPanel,inspectionPanel,salesHoursTable} from './research-activity-ui.mjs?v=051';
import {financePanel,estimateText} from './finance-ui.mjs?v=051';
import {titleScreen} from './title-screen.mjs?v=051';
import {nextResearchStep,completeGuidedStep} from './research-guide.mjs?v=051';
import * as E from './engine.mjs?v=051';
import * as J from './journey-ui.mjs?v=052';
import * as L from './learning.mjs?v=051';
import {roomArt,itemArt,guestArt,portrait,paintArt} from './room.mjs?v=051';
const telemetry=typeof window==='undefined'?{render(){}}:createAnalytics(window,document);telemetry.init?.();
const KEY='renspe.prototype.v3';
let titleVisible=true;
let recapWeek=null,financeMonth=null,inspectionId=null;
let state=E.initialState(),tab='opening',category='all',propertyFloorFilter='preferred',recapStep=0,storageWarning='',timer;
const $=s=>document.querySelector(s), esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen=E.money;
const btn=(action,label,attrs='',cls='primary')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw);if(E.validateState(p)){state=E.migrateFinance(E.migrateEquipment(E.migrateInitialCapital(p)));if(state!==p)localStorage.setItem(KEY,JSON.stringify(state));}else storageWarning='保存データを読み込めませんでした。設定からやり直せます。';}}catch{storageWarning='このブラウザで保存データを読み込めません。';}
let geo={stations:[],error:''},areaFilter={pref:state.areaPref||'東京都',query:'',minimum:'all',page:0},researchTab=state.phase==='research'&&state.research?.checks.length>=5?'forecast':'inspection';
let geographyLoading=false;
async function loadGeography(){if(geographyLoading||geo.stations.length)return;geographyLoading=true;try{const response=await fetch('./data/locations.json');if(!response.ok)throw Error('駅データを取得できません');const data=await response.json();geo={stations:data.stations,error:''};render();}catch(e){geo={stations:[],error:'駅データの読込に失敗しました。再読み込みしてください。'};render();}finally{geographyLoading=false;}}
function clearToast(){clearTimeout(timer);$('#toast').classList.remove('show');$('#toast').textContent='';}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(clearToast,3600);}
function commit(fn){try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);if(E.validateState(x)&&x.revision>state.revision){state=x;render();toast('別の画面の更新を読み込みました。');return false;}}const next=fn(state);next.revision=state.revision+1;localStorage.setItem(KEY,JSON.stringify(next));const previous=state;state=next;clearToast();render();telemetry.progress(previous,next);return true;}catch(e){toast(e.name==='QuotaExceededError'?'保存できませんでした。変更は未確定です。':e.message);return false;}}
function header(){const m=E.monthlyReports(state).at(-1);return `<header><a class="brand" href="#" data-action="top"><img class="game-header-logo" src="assets/web/game-logo-v048.webp" width="1000" height="500" alt="ゲームで学ぶレンスペ経営"></a><div class="header-right"><span class="version">遊べる試作 05.1</span>${btn('settings','設定・やり直す','','text-button')}</div></header>${storageWarning?`<p class="warning">${esc(storageWarning)}</p>`:''}${state.property?`<div class="stats finance-stats"><div><small>手元のお金</small><strong>${yen(state.cash)}</strong></div><div><small>${m?m.month+'ヶ月目の営業利益'+(m.complete?'（確定）':'（途中・'+m.weeks+'/4週）'):'1ヶ月目の営業利益（営業前）'}</small><strong class="${m?.profit<0?'negative':''}">${m?yen(m.profit):'—'}</strong></div><div><small>累計営業利益</small><strong class="${state.totalProfit<0?'negative':''}">${yen(state.totalProfit)}</strong></div><div><small>初期投資${state.initialInvestmentEstimated?'（参考額）':''}</small><strong>${yen(E.initialInvestment(state))}</strong></div><span class="day-note">開業から ${Math.floor(state.completedWeeks/4)}ヶ月${state.completedWeeks%4?'＋'+state.completedWeeks%4+'週':''}<br>回収期限 24ヶ月（96週）</span></div>`:''}`;}
function welcome(){return `<main class="welcome"><div class="intro"><span class="eyebrow">ゲームで、レンスペ経営を学ぶ。</span><h1>はじめての一室。<br>経営を、<br><em>やってみよう。</em></h1><p>ジャンル、立地、物件、競合、収支。<br>契約前から考えて、お客さんを迎える。<br>24ヶ月以内に初期投資を回収して、クリアを目指そう。</p>${btn('start','開業資金200万円で、はじめる →')}<div class="intro-notes"><span>全国47都道府県</span><span>4つのジャンル</span><span>教材の手順を体験</span></div></div><div class="welcome-art">${roomArt('party',['sofa','table','lamp','plant'])}<div class="floating-note">「ここ、使いやすい。<br>また来たいね。」<small>あなたの工夫が、経営の力になる。</small></div></div></main>`;}
function genres(){return `<main><div class="heading"><span class="eyebrow">第1章 / ジャンル選び</span><h1>どんな時間を、つくろう。</h1><p>客層・初期投資・集客・お世話の量が変わります。出店する地域との相性も調べましょう。</p></div>${J.explorationNote(state)}<div class="genre-grid">${E.GENRES.map(g=>`<article class="genre-card">${guestArt(g.id)}<div class="card-body"><span class="eyebrow">${g.name}</span><h2>${g.concept}</h2><p>${g.line}</p><div class="genre-spec"><span>${g.difficulty}</span><span>清掃の目安 週${g.visits}回</span><span>基本料金 ${yen(g.rates[1])} / 時間</span></div>${btn('genre',`${g.name}で始める →`,`data-id="${g.id}" ${state.exploration&&['both','genre'].includes(state.exploration.mode)&&state.exploration.genreId===g.id?'disabled':''}`)}</div></article>`).join('')}</div><p class="footnote">試作では各用途に1つのコンセプト。利用シーンは代表イラストです。</p></main>`;}
function properties(){return J.propertyScreen(state,propertyFloorFilter);}
function equipmentRole(it){return it.role==='common'?'教材：共通の必須品':it.required?'試作の開業セット':it.role==='conditional'?'条件に応じて':it.role==='optional'?'任意':'用途に合わせて追加';}
function kitItems(s,kind){return E.requiredItems(s).filter(i=>!s.owned.includes(i.id)&&(kind==='common'?i.category==='common':i.category!=='common'&&i.id!=='mirror'));}
function roomPane(){
 const g=E.genreOf(state),all=E.catalog(state),required=E.requiredItems(state),left=required.filter(i=>!state.owned.includes(i.id));
 const items=all.filter(i=>category==='all'||category==='common'&&i.category==='common'||category==='genre'&&i.sources&&i.category!=='common'||category==='optional'&&i.sources&&!i.required||category==='care'&&i.category==='care');
 const interior=E.INTERIOR_CHECKS.filter(i=>i.genre===state.genreId);
 return `<div class="pane-head"><span class="eyebrow">付録⑬ ジャンル別 発注リスト</span><h2>使う場面まで、そろえよう。</h2><p>${g.name}の仕様・数量を見ながら購入します。</p></div>
 ${productDisclosure()}<div class="equipment-progress"><b>開業セット ${required.length-left.length} / ${required.length} 品目</b><span>未購入分 ${yen(E.essentialCost(state))}</span></div>
 <p class="small">共通19品は教材の必須品。ジャンル専用の「開業セット」は試作で定めた最低構成です。任意品・条件付きの品は、全て買う必要はありません。金額は教材の初期費用ツールを基にしたゲーム用概算です。</p>
 <div class="equipment-bundles">${[['common','共通の必須品'],['genre',g.name+'の開業セット']].map(([kind,label])=>{const kit=kitItems(state,kind);return `<div><b>${label}</b><p>${kit.length?`未購入 ${kit.length}品 · ${yen(kit.reduce((v,i)=>v+E.itemPrice(state,i),0))}`:'✓ 購入済み'}${kind==='genre'&&g.id==='dance'?'<br>鏡は施工方法を選んで別途手配':''}</p>${btn('kit','内容を確認してまとめて購入',`data-id="${kind}" ${kit.length?'':'disabled'}`,'secondary')}</div>`;}).join('')}</div>
 ${g.id==='dance'&&!state.owned.includes('mirror')?`<div class="note-box"><b>鏡の幅と施工方法を確認</b><p>壁の平滑さ・固定方法を確認して選びます。試作の鏡幅は6.5m。突っ張り式は採用しません。</p>${btn('item','鏡の手配方法を選ぶ','data-id="mirror"','secondary')}</div>`:''}
 <div class="shop-tabs">${[['all','すべて'],['common','共通19品'],['genre','ジャンル専用'],['optional','任意・条件付き'],['care','気配り']].map(([id,t])=>btn('category',t,`data-id="${id}" aria-pressed="${category===id}"`,category===id?'selected':'')).join('')}</div>
 <p class="equipment-scroll-hint">リスト内をスクロールして、備品を確認できます。</p><div class="equipment-list" role="region" aria-label="備品の購入リスト" tabindex="0">${items.map(it=>`<button class="equipment-row ${state.owned.includes(it.id)?'owned':''}" data-action="item" data-id="${it.id}"><span class="equipment-thumbnail">${itemArt(it)}</span><span class="equipment-description"><small>${equipmentRole(it)} · ${esc(it.quantity||'一式')}</small><strong>${esc(it.name)}</strong><span>${esc(it.desc)}</span>${it.condition?`<em>${esc(it.condition)}</em>`:''}</span><b class="equipment-price">${state.owned.includes(it.id)?'✓ 購入済み':yen(E.itemPrice(state,it))}</b></button>`).join('')}</div>
 ${interior.length?`<details class="note-box"><summary>壁・床・照明の発注リスト（内装の手配で対応）</summary>${interior.map(i=>`<p><b>${esc(i.name)}</b><br>${esc(i.note)}</p>${productLinks(i)}`).join('')}${btn('tab','内装の手配へ','data-id="opening"','secondary')}</details>`:''}
 <p class="small">出典：付録⑬の発注リスト（2026年9月11日取得）・教材の初期費用シミュレーター。各品を押すと参照箇所を確認できます。備品の追加が全て売上アップに直結するわけではありません。</p>${L.learnLink('furniture',true)}`;
}
function showKit(kind){const items=kitItems(state,kind);if(!items.length)return;const total=items.reduce((v,i)=>v+E.itemPrice(state,i),0);let issue='';try{E.buyItems(state,items.map(i=>i.id));}catch(e){issue=e.message;}modal(`<span class="eyebrow">未購入品だけを手配</span><h2>${kind==='common'?'共通の必須品':E.genreOf(state).name+'の開業セット'}</h2><p>仕様・数量を確認してください。すでに買った品目は含めません。</p><ul class="kit-checklist">${items.map(i=>`<li><b>${esc(i.name)} <small>${esc(i.quantity)}</small></b><span>${yen(E.itemPrice(state,i))}</span><p>${esc(i.desc)}</p></li>`).join('')}</ul><div class="purchase-total"><span>${items.length}品の合計</span><strong>${yen(total)}</strong></div><p class="small">価格はゲーム用概算。設営費は別途30,000円です。</p>${issue?`<p class="warning">${esc(issue)}</p>`:''}${btn('buy-kit','この内容で購入する',`data-id="${kind}" ${issue?'disabled':''}`)}`);}
function pricingPane(){const g=E.genreOf(state),fee=E.feeRate(state)*(1-E.directShare(state))+E.directShare(state)*.035,fixed=E.weeklyRent(state.property)+E.weeklyUtility(state)+E.weeklyPromotion(state)+E.cleaningFee(state)+E.careCost(state);return `<div class="pane-head"><span class="eyebrow">料金と収支</span><h2>売上の先の、手残りを見る。</h2><p>${g.name}の時間料金。掲載先の手数料は ${(E.feeRate(state)*100).toFixed(0)}%。直予約の決済手数料は3.5%。</p></div><div class="rate-options">${g.rates.map((r,i)=>btn('rate',`<span>${['予約を集める','バランスよく','体験に自信あり'][i]}</span><b>${yen(r)}<small> / 時間</small></b>`,`data-id="${r}" aria-pressed="${state.rate===r}"`,state.rate===r?'rate-card selected':'rate-card')).join('')}</div><div class="note-box"><b>1ヶ月の運営費の目安 ${yen(fixed*4)}</b><p>家賃・共益費 ${yen(E.weeklyRent(state.property)*4)}<br>光熱・通信 ${yen(E.weeklyUtility(state)*4)}<br>HP・広告 ${yen(E.weeklyPromotion(state)*4)}<br>清掃外注 ${yen(E.cleaningFee(state)*4)} ＋ 補充消耗品 ${yen(E.careCost(state)*4)}</p><strong>損益分岐の目安 ${Math.ceil(fixed*4/(state.rate*(1-fee)))}時間 / 月</strong><p class="small">複数ポータルの売上は均等配分の仮定。臨時対応・設備投資を除く。1ヶ月 = 4Wで月額費用を配分します。利益は税・減価償却前の簡易計算です。</p></div>${financePanel(state,financeMonth)}`;}
function meter(label,n){return `<div class="meter"><span>${label}</span><div>${[1,2,3,4,5].map(i=>`<i class="${i<=n?'on':''}"></i>`).join('')}</div><small>${n}/5</small></div>`;}
function staffPane(){const g=E.genreOf(state);if(state.completedWeeks<4)return `<div class="staff-locked">${portrait(0,'locked-portrait')}<span class="eyebrow">清掃外注 / 4W終了で解放</span><h2>まずは、自分でひと回り。</h2><p>${g.care}。<br>4週間で覚えた手順を、清掃の依頼先へ。</p><div class="week-dots">${[1,2,3,4].map(w=>`<span class="${w<=state.completedWeeks?'done':''}">${w}W</span>`).join('')}</div><b>依頼できるまで あと${4-state.completedWeeks}W</b></div>`;
const hired=E.staffOf(state);const idea=hired?E.catalog(state).find(i=>i.id===hired.ideaItem)||E.catalog(state).find(i=>i.id==='guide'):null;
return `<div class="pane-head"><span class="eyebrow">清掃の依頼先</span><h2>お世話を、任せられる日へ。</h2><p>${g.care}。<br>巡回清掃・補充・復元・写真報告を委託します。</p></div>${hired?`<div class="hired-note">${hired.name}さんに週${g.visits}回依頼中 <p>定期依頼をやめても、清掃は実行されません。</p>${btn('release','清掃の定期依頼をやめる','','text-button')}</div>`:''}<div class="staff-list">${E.STAFF.map(p=>`<article class="staff-card">${portrait(p.portrait)}<div><h3>${p.name}<small>${p.age}歳</small></h3><p>${p.line}</p>${meter('スキル',p.skill)}${meter('アイデア',p.idea)}${meter('まじめさ',p.diligence)}<div class="staff-price"><b>${yen(p.visitFee)} / 回</b><span>週${g.visits}回 = ${yen(E.cleaningFee(state,p))} / 週</span>${btn('hire',hired?.id===p.id?'依頼中':'この人に清掃を依頼',`data-id="${p.id}" ${hired?.id===p.id?'disabled':''}`,'secondary')}</div></div></article>`).join('')}</div><div class="note-box"><b>写真つきの清掃マニュアル</b><p>まじめさだけに頼らず、復元と点検の手順を共有。</p>${btn('manual',state.manual?'作成済み':'1,000円で作成',state.manual?'disabled':'','secondary')}</div>${idea&&!state.owned.includes(idea.id)?`<div class="note-box"><b>${hired.name}さんの改善提案</b><p>「${esc(idea.desc)}」</p>${btn('item','提案された備品を見る',`data-id="${idea.id}"`,'text-button')}</div>`:''}<p class="small">スキルは清掃の仕上がり、アイデアは改善提案、まじめさは作業の抜けに関わります。消耗品は委託費と別。電話対応はオーナーが行います。</p>`;}
function ledger(r){return `<dl class="ledger"><div><dt>売上 <small>${r.hours}時間 / 約${r.bookings}件</small></dt><dd>${yen(r.gross)}</dd></div>${[['掲載・決済手数料',r.fee],['家賃・共益費（月額の1/4）',r.rent],['光熱・通信',r.utility],['HP・広告',r.marketing||0],['清掃外注',r.staffCost],['補充・消耗品',r.care],['臨時対応',r.emergency]].map(([t,v])=>`<div><dt>${t}</dt><dd>−${yen(v)}</dd></div>`).join('')}<div class="ledger-total"><dt>営業利益</dt><dd class="${r.profit<0?'negative':''}">${yen(r.profit)}</dd></div></dl><p class="small">ポータル売上 ${yen(r.portalGross||0)} / 直予約 ${yen(r.directGross||0)}</p>${r.rentApplied?`<p class="small">家賃等の${yen(r.rentApplied)}は契約時の前払い分から充当。手元の現金から二重に引きません。</p>`:''}`;}
function recordsPane(){return financePanel(state,financeMonth);}
function marketingPane(){return `<div class="pane-head"><span class="eyebrow">集客を見直す</span><h2>どこから、来てもらう？</h2><p>HPは作るだけで予約が入るわけではありません。運営を重ねると直予約が少しずつ育ちます。</p></div>${E.SETUP_TASKS.filter(t=>['website','ads'].includes(t.id)).map(t=>`<div class="setup-task"><h3>${t.title} / ${t.service}</h3><p>${t.tip}</p>${t.choices.map(c=>btn('setup-choice',`<b>${c.label}</b><span>初期 ${yen(c.cost)} / 月 ${yen((c.weekly||0)*4)}</span><small>${c.detail}</small>`,`data-id="${t.id}:${c.id}" ${state.preparation[t.id]?.id===c.id?'disabled':''}`,'setup-choice')).join('')}</div>`).join('')}<p class="small">変更は次の営業週に反映。この試作では開業後のHP制作期間を1ターンにまとめています。</p>`;}
function management(){const g=E.genreOf(state),p=state.property,st=E.staffOf(state),setup=state.phase==='setup';return `<main class="management"><div class="room-heading"><div><span class="eyebrow">${esc(state.location.pref)} · ${esc(state.location.name)}駅 / ${g.name}</span><h1>${esc(state.name)}</h1><p>${setup?'契約後 '+state.prepDay+'日目':'第'+(state.completedWeeks+1)+'週の運営'}</p></div><p>${p.area}㎡ / ${E.tsubo(p.area).toFixed(2)}坪<br>家賃 ${yen(p.rentMonthly)} / 月 · ${yen(E.tsuboRent(p))} / 坪</p></div>${!setup?weeklyActions(state):''}<div class="management-grid"><section class="room-column"><div class="room-stage">${roomArt(g.id,state.furnished?state.owned:[],true)}<span class="room-caption">${setup&&!state.furnished?'家具を購入したら、開業準備で設営しよう。':'室内は代表イメージ。全ての購入品は下の一覧で確認できます'}</span></div>${layoutNotes(g.id)}<details class="installed-summary"><summary>購入済み ${state.owned.length}品を確認</summary><div class="installed-list">${state.owned.map(id=>{const i=E.ITEMS.find(x=>x.id===id);return btn('item',i.name,`data-id="${id}"`,'installed-chip');}).join('')}</div></details>${J.recovery(state)}<div class="condition"><div><span>清潔さ</span><meter min="0" max="100" value="${state.clean}"></meter><b>${Math.round(state.clean)}</b></div><div><span>備品・補充</span><meter min="0" max="100" value="${state.supplies}"></meter><b>${Math.round(state.supplies)}</b></div></div>${setup?`<div class="end-box"><p>内装・設備だけでなく、掲載・予約管理まで準備します。</p>${btn('tab','開業準備を進める','data-id="opening"')}</div>`:''}</section><section class="control-column"><nav class="main-tabs">${[...(!setup?[['operation','今週の運営']]:[]),['opening',setup?'開業準備':'集客設定'],['room','家具・備品'],['pricing','料金・収支'],['staff','清掃外注'],['records','記録']].map(([id,t])=>btn('tab',t,`data-id="${id}" aria-pressed="${tab===id}"`,tab===id?'selected':'')).join('')}</nav><div class="pane">${tab==='operation'?`<h2>今週の工夫を、ひとつ。</h2><p>清掃・補充を確認できたら、上の「今週の運営を終える」へ。料金・備品・集客の見直しは必要なときに行えます。</p>${btn('tab','月の利益と回収見込みを見る','data-id="pricing"','secondary')}${state.completedWeeks>=4?btn('tab','清掃の依頼先を確認する','data-id="staff"','secondary'):''}`:tab==='opening'?setup?J.openingPane(state):marketingPane():tab==='room'?roomPane():tab==='pricing'?pricingPane():tab==='staff'?staffPane():recordsPane()}</div></section></div></main>`;}
function waiting(){const p=state.pending;return `<main class="waiting"><div class="heading"><span class="eyebrow">THIS WEEK’S WORK IS DONE</span><h1>いってらっしゃい、いい時間。</h1><p>第${p.week}週のお客さんが、入ってきました。</p></div><div class="waiting-scene">${guestArt(state.genreId)}<span>${esc(p.guest.name)} · ${esc(p.guest.purpose)}</span></div><p class="guest-line">「${esc(p.guest.line)}」</p>${p.event?`<div class="call-card"><span class="phone">☎</span><div><b>${p.answer?'対応済み':'お客さんから着信です'}</b><p>${p.event.title}</p></div>${btn('call',p.answer?'対応を見る':'電話に出る','','secondary')}</div>`:'<div class="quiet-note">今のところ、お問い合わせはありません。</div>'}<div class="next-note"><b>今週の運営を確定しました。次の週へ進めましょう。</b><p>次回は、このお客さんの利用中の気持ちを見てみましょう。</p></div><div class="debug-bar"><span>時間を進める</span>${btn('advance','翌週へ +1 Week')}${btn('advance-month','翌月へ +1 Month','','secondary')}</div><p class="footnote">1 Month = 4週間（4ターン分）。翌月へ進むと、途中の3週は追加対応なしで経営が進みます。清掃外注は巡回を継続し、未依頼なら清掃・補充の不足が不満につながります。</p></main>`;}
function recap(){const selection=recapSelection(state,financeMonth,recapWeek),period=selection.period,r=selection.report,result=recapStep>=3,m=r.moments[Math.min(recapStep,2)];return `<main class="recap">${financePanel(state,selection.month)}<section class="period-summary"><p>${selection.month}ヶ月目の利用体験（第${(selection.month-1)*4+1}〜${selection.month*4}週）。上の月を選ぶと、収支と体験が一緒に切り替わります。</p><div class="period-weeks">${period.map(x=>btn('recap-week',`第${x.week}週の体験`,`data-id="${x.week}" aria-pressed="${x.week===r.week}"`,x.week===r.week?'primary':'secondary')).join('')}</div></section><div class="heading"><span class="eyebrow">${selection.month}ヶ月目 · 第${r.week}週 / GUEST STORY</span><h1>${result?'いい時間は、数字にも残る。':'今週の工夫が、届きました。'}</h1><p>${esc(r.guest.name)} · ${esc(r.guest.purpose)}</p></div>${!result?`<div class="story-layout"><div>${guestArt(r.genreId)}<small class="scene-note">${E.genreOf(r.genreId).name}の代表イラスト</small></div><div class="story-copy"><span class="eyebrow">${recapStep+1} / 3 · ${m.title}</span><h2>「${esc(m.line)}」</h2><p>${esc(m.reason)}</p>${btn('story-next',recapStep===2?'今週の結果を見る':'つづきを見る →')}${btn('story-skip','結果へ進む','','text-button')}</div></div>`:`<div class="result-layout"><section><div class="review-card"><span class="eyebrow">お客さんのレビュー</span><div class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</div><h2>「${esc(r.quote)}」</h2><p>${r.review}</p><small>心の声「${r.stars<4?'次は気持ちよく使ってもらえるよう、整えよう。':r.stars===4?'あと1個、どこに置いてきた？':'やってよかった、って思う瞬間。'}」</small></div>${r.event?`<div class="note-box"><b>${r.event.title}</b><p>${r.answer?esc(r.answer.label):'対応が間に合わず、不便が残りました。'}</p></div>`:''}<div class="note-box">${esc(r.staffReport)}</div></section></div>${state.recap.skipped?`<div class="warning">今回進めた第${state.recap.first.week}〜${state.recap.first.week+state.recap.skipped}週は精算済みです。月と週を選んで結果を振り返れます。</div>`:''}${state.recap.unlocked?'<div class="unlock-banner"><b>4W、おつかれさまでした。清掃外注が解放！</b><p>5週目から、巡回清掃・補充・写真報告をお願いできます。</p></div>':''}<div class="recap-continue">${btn('continue',E.gameResult(state)==='gameover'?'24ヶ月の結果を見る →':E.gameResult(state)==='clear'?'クリア結果を見る →':state.recap.unlocked?`第${state.completedWeeks+1}週へ · 清掃の依頼先を見にいく`:`第${state.completedWeeks+1}週の経営へ →`)}</div>`}</main>`;}
function render(){if(!titleVisible&&state.phase==='area'&&!geo.error&&!geo.stations.length)void loadGeography();document.body.classList.toggle('has-week-bar',!titleVisible&&state.phase==='manage');document.title='ゲームで学ぶレンスペ経営｜無料レンタルスペース経営ゲーム';if(titleVisible){$('#app').innerHTML=titleScreen(state,storageWarning);paintArt();telemetry.render(state,"title");return;}$('#app').innerHTML=header()+J.ribbon(state)+L.learningStrip(L.topicFor(state,tab,researchTab))+(state.phase==='welcome'?welcome():state.phase==='genre'?genres():state.phase==='area'?J.areaScreen(state,geo,areaFilter):state.phase==='property'?properties():state.phase==='research'?J.researchScreen(state,researchTab):['setup','manage'].includes(state.phase)?management():state.phase==='waiting'?waiting():state.phase==='gameover'?J.gameoverScreen(state):state.phase==='goal'?J.goalScreen(state):state.phase==='epilogue'?J.epilogueScreen(state):recap())+(!titleVisible&&state.phase==='manage'?mobileWeekBar(state):'')+L.textbookAd(L.topicFor(state,tab,researchTab),{expanded:['goal','epilogue'].includes(state.phase)})+`<footer><span>レンスペ経営シミュレーター / 試作 v0.5.1</span><div>${btn('product-disclosure','商品紹介について','','text-button')}${btn('help','遊び方・データについて','','text-button')}${btn('analytics-info','アクセス解析','','text-button')}</div></footer>`;paintArt();telemetry.render(state,state.phase);}
let previousFocus;
function closeModal(){$('#modal-root').innerHTML='';document.body.classList.remove('modal-open');previousFocus?.focus();}
function modal(content){previousFocus=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-backdrop" data-action="close"><section class="modal" role="dialog" aria-modal="true" aria-label="詳細"><button class="modal-close" data-action="close" aria-label="閉じる">×</button>${content}</section></div>`;document.body.classList.add('modal-open');$('.modal-close').focus();paintArt($('.modal'));telemetry.render(state,titleVisible?"title":state.phase);}
function showResearchGuide(notice=''){
 const step=nextResearchStep(state);if(!step)return;
 if(step.section)researchTab=step.section;render();
 if(step.action==='observe'){showComparison();return;}
 if(step.action==='repeat-survey'){modal(calendarPanel(state));return;}
 if(step.action==='survey'&&inspectionQuestion(state,step.id)){showInspectionDecision(step.id);return;}
 const scene=step.action==='survey'?inspectionScene(state,step.id):step.key==='visit'?inspectionScene(state,'visit'):'';
 const f=step.key==='forecast'?E.forecast(state):null;
 modal(`<span class="eyebrow">確認項目 · ${Math.min(step.done+1,step.total)}/${step.total}</span>${notice?`<p class="guide-success" role="status">✓ ${esc(notice)}</p>`:''}<h2>${esc(step.title)}</h2>${scene}<p>${esc(step.body)}</p>${f?`<div class="guide-forecast">${f.cases.map(c=>`<p><b>${c.name}：${yen(c.profit)} / 月</b><br>回収目安：${c.months?c.months+'ヶ月':'この条件では回収できない'}</p>`).join('')}</div>`:''}${btn('guide-confirm',esc(step.label),`data-id="${step.key}"`)}${['forecast','contract'].includes(step.key)?btn('guide-leave','契約せず、別の物件を見る','','secondary'):''}${btn('close','いったん閉じて、資料を見直す','','text-button')}`);
}
function showComparison(selected=null){modal(comparisonPanel(state,selected));$('.modal').classList.add('activity-wide');}
function showResearchOutcome(title,detail,takeaway=''){
 const step=nextResearchStep(state),notes=`<div class="observation-result">${String(detail).split('\n').map(line=>`<p>${esc(line)}</p>`).join('')}</div>`;
 modal(`<span class="eyebrow">調査ノートに記録しました</span><h2>${esc(title)}</h2>${takeaway?`<p class="quiz-takeaway">${esc(takeaway)}</p><details class="quiz-details"><summary>内見メモを詳しく見る</summary>${notes}</details>`:notes}<p class="small">学習用の架空の観察結果です。</p>${step?btn('guide-next',`次は「${esc(step.action==='observe'?'5店を比較':step.action==='repeat-survey'?'予約の変化を観察':step.title)}」へ`):''}${btn('close','調査ノート全体を見る','','text-button')}`);
}
function showInspectionDecision(id,notice=''){
 const q=inspectionQuestion(state,id);if(!q)return;inspectionId=id;
 modal(inspectionPanel(state,q,notice));
}
function showResearchDecision(notice=''){
 const missing=E.researchRequirements(state).filter(x=>!x.done);if(missing.length){showResearchGuide();return;}
 const c=E.competitors(state).find(x=>x.id===state.research.benchmark);
 modal(`<span class="eyebrow">かんたん確認 / 売上の計算</span><h2>売上になるのは、何時間？</h2><p>${esc(c.name)}の1週間の予定です。</p>${salesHoursTable(c)}${notice?`<p role="status" class="warning">${esc(notice)}</p>`:''}<div class="calendar-answers">${[c.hours+c.blocked+c.buffer,c.hours].map(v=>btn('research-answer',`${v}時間`,`data-id="${v}"`,'choice-card')).join('')}</div><p class="small">ゲーム内の比較例です。間違えても資金は減りません。</p>`);
}
function showItem(id){if(!['setup','manage'].includes(state.phase))return;const it=E.catalog(state).find(i=>i.id===id);if(!it)return;const owned=state.owned.includes(id),price=E.itemPrice(state,it),can=state.cash-price>=E.purchaseReserve(state,id);
 const mirrorChoices=id==='mirror'&&!owned?(state.property.existingMirror?[['existing','内見で確認した既存鏡を利用',0]]:[['panel','ビス固定パネルをDIYで施工',214500],['contractor','鏡の施工業者へ依頼',533000]]):null;
 modal(`<div class="modal-item-art">${itemArt(it)}</div><span class="eyebrow">${equipmentRole(it)} · ${esc(it.quantity||'一式')}</span><h2>${esc(it.name)}</h2><p>${esc(it.desc)}</p>${it.condition?`<div class="note-box">${esc(it.condition)}</div>`:''}<p class="small">${esc(it.priceBasis||'ゲーム用の概算価格')} ${it.sources?'<br>付録⑬ '+it.sources.map(x=>esc(x.sheet+' '+x.range)).join(' / '):''}</p>${owned?'<b class="installed">✓ 購入済み</b>':mirrorChoices?`<p>幅6.5mで比較。平滑な壁への確実な固定が前提です。実際の幅・施工条件で見積もりは変わります。</p>${mirrorChoices.map(([method,label,cost])=>{let issue='';try{E.buyMirror(state,method);}catch(e){issue=e.message;}return btn('buy-mirror',`<b>${label} · ${yen(cost)}</b>${issue?'<small>'+esc(issue)+'</small>':''}`,`data-id="${method}" ${issue?'disabled':''}`,'choice-card');}).join('')}`:`<div class="purchase-total"><span>ゲーム内の購入価格</span><strong>${yen(price)}</strong></div><p class="small">購入後の現金 ${yen(state.cash-price)}<br>確保する開業・運転資金 ${yen(E.purchaseReserve(state,id))}</p>${btn('buy',can?'ゲーム内で購入する':'運転資金を残しましょう',`data-id="${id}" ${can?'':'disabled'}`)}`}${L.realEquipmentBridge(it)}`);}
function showCall(){const p=state.pending;if(!p?.event)return;modal(`<span class="eyebrow">${p.answer?'対応済み':'お客さんからの電話'}</span><h2>${p.event.title}</h2><p class="call-question">「${esc(p.event.question)}」</p><p class="inner-voice">心の声「${esc(p.event.inner)}」</p>${p.answer?`<div class="note-box">${esc(p.answer.label)}。利用結果に反映します。</div>`:p.event.choices.map(c=>btn('answer',`${c.label}${c.requires&&!p.snapshot.owned.includes(c.requires)?'<small>必要な備品が未設置です</small>':''}`,`data-id="${c.id}" ${c.requires&&!p.snapshot.owned.includes(c.requires)?'disabled':''}`,'choice-card')).join('')}`);}
function settings(){modal(`<span class="eyebrow">試作の設定</span><h2>もう一度、別の部屋から。</h2><p>物件の引き直しは、契約前の画面から何度でもできます。用途も含めてやり直すなら、リセットしてください。</p>${state.phase==='property'?btn('reroll','物件だけ引き直す','','secondary'):''}${btn('reset-check','最初からリセマラする','','primary')}${btn('launch-title','タイトル画面へ戻る','','secondary')}<p class="small">このブラウザに自動保存。v0.1・v0.2のセーブは別に残しています。翌週・翌月への送りは、今週の運営を終えた画面にあります。</p>`);}
function help(){modal(`<h2>開業前から、初期費用回収まで。</h2><ol><li>ジャンル → 都道府県・駅 → 物件候補。</li><li>用途別の内見項目、競合5店の継続調査、実際に1店を利用。</li><li>弱気・標準・好調の利益を試算して契約。</li><li>電気・水道・任意のガス、回線、内装を手配。家具購入・設営・写真・掲載・予約管理を準備。</li><li>HPと広告を使うか選び、オープン。</li><li>清掃・顧客対応・改善・収支確認。4W後に清掃外注。</li><li>開業から24ヶ月（96週）以内に初期投資＋追加投資を営業キャッシュで回収すればクリア。96週目までに回収できなければゲームオーバー。その先の出店はクリア後に選べます。</li></ol><p>1ターン=1週間、4週間=ゲーム内1ヶ月。「翌週へ +1 Week」で1週、「翌月へ +1 Month」で4週進みます。実際の日付が変わるのを待つ必要はありません。開業前の工事日数は別の準備時計です。</p><p>駅データは国土数値情報の2024年度値。物件・競合・金額・需要は学習用の仮定です。実際の収益を保証するものではありません。</p><p class="small">サービス名は架空の仮名。実サービスに登録・支払いはしません。2店舗同時運営、実際の電話通知、家具の自由配置は未実装です。</p>`);}
document.addEventListener('click',e=>{const t=e.target.closest('[data-action]');if(!t||t.disabled)return;const a=t.dataset.action,id=t.dataset.id;if(a==='close'&&t.classList.contains('modal-backdrop')&&e.target!==t)return;e.preventDefault();if(e.detail>1&&['guide-confirm','guide-next','inspection-answer','calendar-answer','compare-save'].includes(a))return;switch(a){
case 'analytics-info':modal(analyticsNotice(telemetry.isDisabled()));break;
case 'analytics-disable':telemetry.disable();modal(analyticsNotice(true));break;
case 'analytics-enable':telemetry.enable();break;
case 'product-disclosure':modal(productDisclosure()+btn('close','ゲームに戻る','','secondary'));break;
case 'guide-next':showResearchGuide();break;
case 'property-floor':propertyFloorFilter=id;render();break;
case 'guide-confirm':{if(id.startsWith('survey:')&&inspectionQuestion(state,id.slice(7))){showInspectionDecision(id.slice(7));break;}if(id==='forecast'&&!state.research.calendarLearned){showResearchDecision();break;}const finding=id.startsWith('survey:')?E.inspectionFinding(state,id.slice(7)):'';if(commit(s=>completeGuidedStep(s,id))){closeModal();if(state.phase==='research')showResearchOutcome(finding?'現地で分かったこと':id==='visit'?'お客さんとして、使ってみました':'試算を確認しました',finding||(id==='visit'?E.visitFinding(state):'弱気のケースも踏まえて、次は契約するかを決めます。'));else{tab='opening';render();window.scrollTo(0,0);if(state.phase==='setup')modal(`<span class="eyebrow">契約が完了しました</span><h2>次は、開業準備です。</h2><p>まず「電気」「水道」「ガスを使うか」「回線」を選びます。続けて内装・家具・写真・掲載を準備しましょう。</p>${btn('close','開業準備を始める →')}`);}}break;}
case 'guide-leave':if(commit(s=>({...s,phase:'property',research:null}))){closeModal();window.scrollTo(0,0);}break;
case 'learn':telemetry.emit('game_lesson_open',{...analyticsContext(state,titleVisible?'title':state.phase),game_topic:id});modal(L.lessonPanel(id,{genreId:state.genreId}));break;
case 'item-learn':if(E.catalog(state).some(i=>i.id===id))modal(L.lessonPanel('furniture',{returnItem:id,genreId:state.genreId}));break;
case 'next-experience':if(commit(s=>E.startNextExperience(s,id))){tab='opening';category='all';researchTab='inspection';areaFilter={pref:state.exploration.pref,query:'',minimum:'all',page:0};window.scrollTo(0,0);}break;
case 'top':case 'launch-title':titleVisible=true;closeModal();render();window.scrollTo(0,0);break;
case 'launch-continue':telemetry.play(state,true);titleVisible=false;if(state.phase==='manage')tab='operation';render();window.scrollTo(0,0);break;
case 'start':case 'genres':if(commit(s=>({...s,phase:'genre'}))){telemetry.play(state);titleVisible=false;render();window.scrollTo(0,0);}break;
case 'genre':areaFilter.page=0;if(commit(s=>E.chooseGenre(s,id)))window.scrollTo(0,0);break;
case 'reload-geography':loadGeography();break;
case 'map-pref':{const next=selectMapPrefecture(areaFilter,id);if(next!==areaFilter){areaFilter=next;render();}break;}
case 'map-region':if(id==='all'||MAP_REGIONS.some(r=>r.id===id)){areaFilter={...areaFilter,mapZoom:id,mapRegion:id==='all'?undefined:id};render();}break;
case 'map-stations':$('#station-browser')?.focus();$('#station-browser')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});break;
case 'filter-stations':areaFilter={...areaFilter,pref:$('#prefecture').value,query:$('#station-query').value.trim(),minimum:$('#station-minimum').value,page:0};render();break;
case 'station-page':areaFilter.page=Number(id);render();$('#station-browser')?.focus();$('#station-browser')?.scrollIntoView({block:'start'});break;
case 'areas':commit(s=>({...s,phase:'area',research:null}));window.scrollTo(0,0);break;
case 'station':if(commit(s=>E.chooseArea(s,geo.stations.find(x=>x.id===id))))window.scrollTo(0,0);break;
case 'research':{const name=$('#store-name')?.value||state.name;researchTab='inspection';if(commit(s=>({...E.startResearch(s,id),name})))window.scrollTo(0,0);break;}
case 'research-tab':researchTab=id;render();window.scrollTo(0,0);break;
case 'back-properties':if(commit(s=>({...s,phase:'property',research:null})))window.scrollTo(0,0);break;
case 'inspection-answer':{const q=inspectionQuestion(state,inspectionId);if(!q)break;telemetry.emit('game_quiz_answer',{...analyticsContext(state,state.phase),game_topic:inspectionId,game_result:Number(id)===q.answer?'correct':'retry'});if(Number(id)!==q.answer){showInspectionDecision(inspectionId,q.explanation);break;}if(commit(s=>answerInspection(s,inspectionId,id)))showResearchOutcome('正解！ここがポイント',E.inspectionFinding(state,inspectionId),q.explanation);break;}
case 'survey':if(inspectionQuestion(state,id)){showInspectionDecision(id);break;}if(commit(s=>E.survey(s,id)))showResearchOutcome('現地で分かったこと',E.inspectionFinding(state,id));break;
case 'compare-select':showComparison(id);break;
case 'compare-save':if(commit(s=>completeComparison(s,id)))showResearchOutcome('5店の違いを、ひとつの比較に',E.competitors(state).find(c=>c.id===id).lesson+' 次は、同じ週の予約があとから増える様子を追います。');break;
case 'calendar-answer':{const c=E.competitors(state).find(c=>c.id===state.research.benchmark);if(Number(id)!==c.hours){modal(calendarPanel(state,'売上になるのは、お客さんが利用する時間だけです。'));break;}if(commit(s=>completeCalendar(s,id)))showResearchOutcome('予約の増え方まで、調査できました',`売上に数えるのは${c.hours}時間。初回の${c.firstHours}時間だけでも、埋まった時間すべてでもありません。次は実際に使って、数字では分からない体験を確かめます。`);break;}
case 'observe':commit(s=>E.observe(s,id));break;
case 'repeat-survey':commit(E.repeatSurvey);break;
case 'visit-competitor':if(commit(s=>E.visitCompetitor(s,id)))showResearchOutcome('お客さんとして、使ってみました',E.visitFinding(state));break;
case 'benchmark':commit(s=>E.setBenchmark(s,id));break;
case 'accept-forecast':if(state.research.calendarLearned)showResearchGuide();else showResearchDecision();break;
case 'research-answer':{const c=E.competitors(state).find(x=>x.id===state.research.benchmark);if(Number(id)!==c.hours){showResearchDecision('売上になるのは、お客さんが利用する時間だけです。');break;}if(commit(E.acceptForecast))showResearchGuide(`判断できました。予約${c.hours}時間だけを売上に数えます。標準予測だけでなく弱気の回収期間も踏まえて、契約するかを決めましょう。`);break;}
case 'setup-choice':{const [task,choice]=id.split(':');if(commit(s=>E.chooseSetup(s,task,choice)))toast('手配内容を保存しました。');break;}
case 'finish-prep':if(commit(E.finishPreparation))toast('手配した作業が完了しました。待機中の賃料を計上しました。');break;
case 'assemble':if(commit(E.assemble))toast(E.equipmentChecked(state)?'設営と開通後の動作確認を終えました。':'組立・固定が完了。電気・水道・回線の開通後に動作確認しましょう。');break;
case 'verify-equipment':if(commit(E.verifyEquipment))toast('通電・通水・Wi-Fi・音源・入室案内を確認しました。');break;
case 'recap-week':recapWeek=Number(id);financeMonth=Math.ceil(recapWeek/4);recapStep=3;render();break;
case 'register-portal':commit(s=>E.registerPortal(s,id));break;
case 'sync-calendar':commit(E.syncCalendar);break;
case 'epilogue':if(commit(s=>E.epilogue(s,id)))window.scrollTo(0,0);break;
case 'keep-managing':tab='records';commit(s=>({...s,phase:'epilogue'}));break;
case 'reroll':if(commit(E.reroll)){closeModal();toast('新しい候補を見つけました。もう一度、条件を確かめましょう。');}break;
case 'inspect':{const name=$('#store-name')?.value||state.name;commit(s=>({...E.inspect(s,id),name}));break;}
case 'contract':{tab='opening';const name=$('#store-name')?.value;if(commit(s=>E.contract(s,id,name)))window.scrollTo(0,0);break;}
case 'tab':tab=id;render();if(innerWidth<850)document.querySelector('.control-column').scrollIntoView({behavior:'smooth'});break;
case 'category':category=id;render();break;
case 'item':showItem(id);break;
case 'kit':showKit(id);break;
case 'buy-kit':if(commit(s=>E.buyItems(s,kitItems(s,id).map(i=>i.id)))){closeModal();toast('未購入の備品を手配しました。内装完了後に設営しましょう。');}break;
case 'buy-mirror':if(commit(s=>E.buyMirror(s,id))){closeModal();toast('鏡を手配しました。固定と安全を設営時に確認します。');}break;
case 'buy':if(commit(s=>E.buy(s,id))){closeModal();toast('購入しました。開業準備中は、設営で部屋に反映します。');}break;
case 'rate':commit(s=>E.setRate(s,Number(id)));break;
case 'care':if(commit(E.prepare))toast('今週の巡回清掃と補充を手配しました。');break;
case 'open':tab='operation';if(commit(E.openStore)){toast('開業しました。最初のお客さんを迎えましょう。');window.scrollTo(0,0);}break;
case 'end':if(commit(E.endTurn))window.scrollTo(0,0);break;
case 'advance':case 'advance-month':recapStep=0;financeMonth=null;recapWeek=null;if(commit(s=>E.advanceWeeks(s,a==='advance-month'?4:1)))window.scrollTo(0,0);break;
case 'call':showCall();break;
case 'answer':if(commit(s=>E.answerCall(s,id)))showCall();break;
case 'story-next':recapStep++;render();break;
case 'story-skip':recapStep=3;render();break;
case 'continue':tab=state.recap.unlocked?'staff':'operation';if(commit(E.continueManagement))window.scrollTo(0,0);break;
case 'hire':if(commit(s=>E.hire(s,id)))toast(E.staffOf(state).name+'さんに巡回清掃を依頼しました。');break;
case 'release':if(commit(E.release))toast(state.careDone?'定期依頼を終了しました。今週の自分での清掃・補充は手配済みです。':'定期依頼を終了しました。今週の清掃・補充は未手配です。');break;
case 'manual':if(commit(E.makeManual))toast('写真つきの清掃手順を共有しました。');break;
case 'finance-month':financeMonth=Number(id);recapWeek=null;if(state.phase==='recap')recapStep=3;render();break;
case 'report':{const r=state.reports.find(r=>r.week===Number(id));if(r)modal(`<span class="eyebrow">第${r.week}週</span><h2>「${esc(r.quote)}」</h2><p>${esc(r.guest.name)} / ${'★'.repeat(r.stars)}</p>${ledger(r)}<p>${esc(r.staffReport)}</p>`);break;}
case 'settings':settings();break;
case 'help':help();break;
case 'close':closeModal();break;
case 'reset-check':modal(`<h2>新しい経営を、最初から？</h2><p>現在の部屋・お金・達成アルバムをリセットし、新しい物件候補で用途選びから始めます。</p>${btn('reset','リセットして用途を選ぶ')}${btn('close','今の部屋を続ける','','secondary')}`);break;
case 'reset':if(commit(s=>({...E.initialState(),phase:'genre',revision:s.revision}))){titleVisible=false;tab='opening';category='all';recapStep=0;financeMonth=null;recapWeek=null;closeModal();render();window.scrollTo(0,0);}break;
}});
document.addEventListener('change',e=>{if(e.target.id==='prefecture'){areaFilter={...selectMapPrefecture(areaFilter,e.target.value),mapZoom:'all'};render();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='Tab'&&$('.modal')){const b=[...$('.modal').querySelectorAll('button:not(:disabled),input,a')],first=b[0],last=b.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const n=JSON.parse(e.newValue);if(E.validateState(n)){state=n;closeModal();render();}}catch{}}});
render();

document.addEventListener('click',e=>{const a=e.target.closest?.('a[href]');if(a)telemetry.click(a,state,titleVisible?'title':state.phase);},true);
document.addEventListener('toggle',()=>telemetry.render(state,titleVisible?'title':state.phase),true);
