import {productLinks,linksFor} from './product-links.mjs?v=051';
import {BRIDGES} from './learning-bridges.mjs?v=051';
export {BRIDGES};
const ROOT='https://rental-space.net';
const article=(slug,label)=>({url:`${ROOT}/articles/${slug}.html`,label});
const genre=article('2026-02-15-how-to-start-genre-selection','ジャンルごとの特徴と選び方');
const property=article('2026-02-21-how-to-start-property-hunting','儲かる物件を探す手順');
const inspect=article('2026-02-13-dont-compromise-on-property','物件で妥協してはいけない条件');
const competitor=article('2026-08-18-competitor-visit-before-opening','契約前に競合を利用して確かめる');
const profit=article('2026-09-03-rent-100k-profit','家賃から手残りを計算する');
const opening=article('2026-09-01-rental-studio-opening-guide','レンタルスタジオの開業手順');
const interior=article('2026-02-02-interior-contractor-selection','内装業者の選び方とDIYの線引き');
const portal=article('2026-02-07-portal-site-selection','掲載先と予約カレンダーの管理');
const cleaning=article('2026-02-03-cleaning-outsourcing','清掃外注の探し方・依頼の仕方');
const operation=article('2026-08-26-rental-space-after-opening','オープン後にする3つの仕事');
export const LESSONS={
 danceProperty:{title:'ダンスの物件選び',chapter:'第2部2-5・2-7・2-8',intro:'階数の名前ではなく、音と振動の伝わり先を見る。',points:['まず地下・1階、階下にフロアがない物件を中心に探します。1階に地下テナントがある場合も含め、上下左右の用途を確かめます。','仲介担当と分かれ、音楽・ジャンプ・足音を確認。RC造、階下が倉庫・楽器教室、今は空室というだけでは合格にしません。空中階は確認できた場合の例外です。','地下は湿気・カビ跡・換気・携帯電波を確認。契約後の高額な防音防振工事を前提に、合わない物件を借りないことも経営の判断です。'],articles:[article('2026-08-23-dance-studio-property-search','ダンス物件の検索条件と選別基準'),article('2026-02-22-how-to-start-interior-negotiation','音・振動の確認と契約条件の交渉')]},
 genre:{title:'ジャンル選定',chapter:'第1部',intro:'好きな部屋と、続けられる経営を重ねよう。',points:['パーティーは飲食後の清掃、ダンスは床・鏡と音や振動への配慮など、ジャンルで仕事が変わります。','初期費用・必要な広さ・集客・リピートの仕方を比べて選びます。'],articles:[genre]},
 area:{title:'立地・商圏',chapter:'第2部',intro:'駅の人数だけで出店を決めない。',points:['ダンスの乗降客数は候補を絞る目安。徒歩経路、住宅地の需要、競合も確かめます。','パーティー・会議室は近い条件の競合の利益、撮影は目的を持って来てもらえる理由を調べます。'],articles:[property,genre]},
 property:{title:'物件選び',chapter:'第2部',intro:'毎月出ていくお金を、契約前に見極める。',points:['敷金・礼金はジャンルで固定せず、募集ごとの月数と金額を比較。敷引きは戻らないお金です。原状回復と解約予告も確認します。','業種の可否、無人運営、不特定多数の出入りを伝え、貸主の承認を確かめます。'],articles:[property,inspect,article('2026-08-25-rental-space-startup-cost','敷金・礼金・敷引きと初期費用の違い')]},
 inspection:{title:'内見のチェック',chapter:'第2部・付録⑤',intro:'写真で分からない条件を、現地で確かめよう。',points:['駅から歩き、搬入口と家具の幅、実際に使える面積、電源・回線を確認します。','音・振動、鍵、残置物、原状回復の条件も記録。「安い」だけで決めないことが大切です。'],articles:[inspect,competitor]},
 market:{title:'競合調査・利用視察',chapter:'第3部',intro:'写真を見るだけでは分からない経営がある。',points:['条件の近い基準店と上位・下位店の計5店を比べ、複数日にわたって予約状況を確認します。','オーナーブロック・入替余白を除いて推計し、1店は実際に使って、動線・案内・備品を確かめます。'],articles:[competitor]},
 forecast:{title:'利益シミュレーション',chapter:'第3部・第7部',intro:'売上から、手数料と経費を引く。',points:['弱気・標準・好調のケースで、家賃・光熱通信・清掃外注を引いた手残りを比べます。','開業費を何ヶ月で回収できるか、赤字の期間を支える現金が残るかを契約前に確認します。'],articles:[profit]},
 opening:{title:'開業の段取り',chapter:'第4部',intro:'手配の順番で、待ち時間の家賃が変わる。',points:['回線や内装など時間のかかる手配から進め、その間に家具・備品をそろえます。','設営・動作確認・掲載写真・予約管理を整えてオープン。使える既存設備は活かします。'],articles:[opening,interior]},
 utilities:{title:'ライフライン・Wi-Fiの手配',chapter:'第4部4-6',intro:'客が使える日から逆算して手配する。',points:['電気・水道・通信の利用開始と、空調・機材の容量を確認します。ガスは用途に応じて選びます。','回線の工事日と内装・搬入を並行して調整し、開通後は実機で接続を確認します。'],articles:[opening]},
 interior:{title:'内装と施工業者選び',chapter:'第4部4-3〜4-4',intro:'必要な工事と、好みで足す工事を見分ける。',points:['現地を見てもらい、施工範囲・追加費用・原状回復をそろえて見積りを比較します。','塗装など自分でできる作業と、電気・構造・重量物など専門家に頼む作業を分けます。'],articles:[interior]},
 furniture:{title:'家具・備品と設営',chapter:'付録⑬ ジャンル別 発注リスト・初期費用ツール',intro:'教材の発注リストから、用途・仕様・数量を確認しよう。',points:['全ジャンル共通19品を先に確認。防犯カメラは双方向通話、予備鍵、清掃用品、充電ケーブルまで含みます。','ダンスはCD・Bluetooth・USB・AUX対応の音楽プレーヤー、予備を含む三脚、無料ヨガマット。小さな個人練習室ならホワイトボードは不要です。','撮影は3台以上の三脚、衣装ラック、更衣スペース。会議はしっかりした長机、人数分と予備の椅子、変換アダプター。パーティーはゲーム機・人数分と予備のコントローラーなど、使う場面まで確認します。','入室案内や復元写真は少額の工夫。家具の値段だけで満足度が決まるわけではありません。'],articles:[opening,operation]},
 marketing:{title:'掲載・集客・公式HP',chapter:'第5部',intro:'予約の入口と、手数料を比べよう。',points:['使い方が伝わる写真と案内を用意し、複数サイトの予約が重ならないようカレンダーを管理します。','HPや広告は必要に応じて追加。作るだけで売上が増えるとは限らず、予約と費用を照らし合わせます。'],articles:[portal,profit]},
 cleaning:{title:'清掃の外注',chapter:'第6部6-2〜6-4',intro:'「きれいに」だけでは、依頼内容は伝わらない。',points:['清掃・補充・家具の復元・写真報告を具体的に決め、写真つきマニュアルを共有します。','1回の料金と必要な巡回回数を比べます。採用後も報告を見て、手順や依頼範囲を改善します。'],articles:[cleaning]},
 operation:{title:'顧客対応と日々の運営',chapter:'第6部',intro:'困りごとへの対応を、次の仕組みに変える。',points:['入室できない・備品が動かないときは、まず状況と代替手段を確認します。','対応して終わりにせず、予備鍵、写真案内、補充ルールを整え、同じ困りごとを減らします。'],articles:[operation,cleaning]},
 review:{title:'お客さんの声と改善',chapter:'第5部・第6部',intro:'喜ばれた工夫も、不便だった点も、次に活かす。',points:['レビューの点数だけでなく、利用中のどの行動で喜び・不便が生まれたかを見ます。','案内・復元写真・予備備品など小さな改善から試し、収支と再利用の変化を確認します。'],articles:[operation]},
 recovery:{title:'収支確認・初期費用回収',chapter:'第3部・第7部',intro:'月ごとの黒字と、投資の回収は別のもの。',points:['投じた現金に対し、経営でいくら取り戻せたかを積み上げて確認します。','敷金・設備投資・前家賃を区別します。ゲームでも前家賃を二重に支払わない計算にしています。'],articles:[profit]},
 expansion:{title:'2店目の立地・ジャンル選び',chapter:'第8部・第1〜3部',intro:'次の一室で、別の経営の形を学ぼう。',points:['違うジャンルを選ぶと、設備・客層・清掃・集客の条件が変わります。','同じジャンルでも、駅が変われば家賃と需要は変わります。次も競合調査と試算から始めます。'],articles:[genre,competitor]}
};
export function topicFor(s,tab='opening',research='inspection'){if(['welcome','genre'].includes(s.phase))return 'genre';if(s.phase==='area')return 'area';if(s.phase==='property')return s.genreId==='dance'?'danceProperty':'property';if(s.phase==='research')return research==='inspection'&&s.genreId==='dance'?'danceProperty':research;if(['setup','manage'].includes(s.phase))return tab==='operation'?'operation':tab==='room'?'furniture':tab==='pricing'?'forecast':tab==='staff'?'cleaning':tab==='records'?'recovery':s.phase==='setup'?'opening':'marketing';return s.phase==='waiting'?'operation':s.phase==='recap'?'review':['goal','gameover'].includes(s.phase)?'recovery':'expansion';}
export const topicForTask=id=>['power','water','gas','internet'].includes(id)?'utilities':id==='interior'?'interior':['photos','website','ads'].includes(id)?'marketing':'opening';
export function textbookURL(topic,placement='guide',anchor=''){const u=new URL(`${ROOT}/kyokasho/`);u.search=new URLSearchParams({utm_source:'renspe_game',utm_medium:'in_game',utm_campaign:'learn_management',utm_content:`${placement}_${topic}`}).toString();u.hash=anchor||(placement==='chapter'?'contents':'');return u.href;}
export function learnLink(id,compact=false){return `<button class="learn-link" data-action="learn" data-id="${id}"><span aria-hidden="true">▤</span> ${LESSONS[id].title}について学ぶ${compact?'':' →'}</button>`;}
export function learningStrip(topic){return `<aside class="learning-strip"><div><small>この場面の判断に迷ったら</small>${learnLink(topic)}</div><span>無料の要点をゲーム内で確認</span></aside>`;}
function bookPanel(id,placement='chapter'){const b=BRIDGES[id],l=LESSONS[id];return `<div class="lesson-book"><span class="ad-label">広告｜制作者の教材</span><h3>${b.title}</h3><p>${b.detail}</p><p class="book-product">レンタルスペース経営の教科書 <small>有料Web教材 · ${l.chapter}</small></p><div class="book-actions"><a class="book-link" href="${textbookURL(id,placement,b.anchor)}" target="_blank" rel="noopener noreferrer">教材の内容・付録を見る ↗</a><a class="sample-link" href="${textbookURL(id,'sample','sample')}" target="_blank" rel="noopener noreferrer">まず無料の試し読みへ ↗</a></div><small>教材の紹介ページを別タブで開きます。価格・購入条件はリンク先へ。ゲームは購入せず最後まで遊べます。</small></div>`;}
export function lessonPanel(id,{returnItem=null,genreId=null}={}){const l=LESSONS[id];if(!l)return '';const purpose={party:'パーティー：ゲーム機は人数分と予備のコントローラーまで。飲食後の片付け・ゴミ処理と合わせて備品を考えます。',photo:'撮影：3台以上の三脚、衣装ラック、更衣スペース。背景・照明・撮影距離も合わせて確認します。',meeting:'会議室：しっかりした長机、人数分と予備の椅子、全席への電源、変換アダプターまで確認します。',dance:l.points[1]}[genreId];const points=id==='furniture'&&purpose?[l.points[0],purpose,l.points[3]]:l.points;return `<span class="eyebrow">無料の学習ノート</span><h2>${l.title}について学ぶ</h2><p class="lesson-intro">${l.intro}</p><ol class="lesson-points">${points.map(p=>`<li>${p}</li>`).join('')}</ol><div class="lesson-reading"><b>無料記事で、実例を読む</b>${l.articles.map(a=>`<a href="${a.url}" target="_blank" rel="noopener noreferrer">${a.label} <span>↗</span></a>`).join('')}<small>ブログを別タブで開きます。読み終えたら、このゲームのタブへ戻れます。</small></div>${bookPanel(id)}<div class="lesson-return"><button class="secondary" data-action="${returnItem?'item':'close'}" ${returnItem?`data-id="${returnItem}"`:''}>${returnItem?'備品の詳細に戻る':'ゲームに戻る'}</button><small>戻る操作で週や資金は変わりません。</small></div>`;}
export function textbookAd(topic,{expanded=false}={}){if(!BRIDGES[topic])return '';return `<aside class="textbook-ad contextual-ad" aria-label="広告 制作者の教材"><details ${expanded?'open':''}><summary><span class="ad-label">広告｜制作者の教材</span><span>${BRIDGES[topic].title}</span><small>紹介を開く</small></summary>${bookPanel(topic,'footer')}</details></aside>`;}
export function realEquipmentBridge(item){return `<details class="real-equipment"><summary>${linksFor(item).length?'実際の備品選び・参考商品を見る':'実際の備品選びにも活かす'}</summary><p>現実の部屋では、${item.quantity||'必要な数量'}・寸法・設置条件を確認して選びます。表示中の価格はゲーム用の概算です。</p>${productLinks(item)}<button class="learn-link" data-action="item-learn" data-id="${item.id}">無料の備品選びの要点・教材の発注リスト紹介 →</button></details>`;}
