import {MOODS,ROLE_NAMES,CSS_ROLES,normalizeHex,rgb,contrast,inkFor,generatePalettes,extractColors,exportData,exportPrompt,exportCss} from './engine.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={count:3,mood:'natural',source:'mood',base:'#52796F',imageColors:[],comment:'',locks:{},seed:0,palettes:[],selected:0,view:'web',format:'prompt',history:[],favorites:[]};
let toastTimer,imageUrl=null;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200);}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function swatches(colors,className){const div=el('div',className);for(const c of colors){const i=el('i');i.style.setProperty('--s',c);div.append(i);}return div;}
function palette(){return state.palettes[state.selected];}
function stash(){if(!palette())return;state.history.push(JSON.stringify({palettes:state.palettes,selected:state.selected,locks:state.locks,count:palette().colors.length}));if(state.history.length>20)state.history.shift();$('#undo').disabled=false;}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('コピーしました');}catch{const field=el('textarea');field.value=text;field.style.cssText='position:fixed;left:0;top:0;opacity:0';document.body.append(field);field.select();let ok=false;try{ok=document.execCommand('copy')}catch{}field.remove();toast(ok?'コピーしました':'コピーできませんでした。出力欄の文字を選択してコピーしてください。');}}
function setSource(source){state.source=source;$$('[data-source]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.source===source));for(const name of ['mood','color','image'])$('#'+name+'-panel').hidden=name!==source;}
function updateMood(){for(const b of $$('[data-mood]'))b.setAttribute('aria-pressed',b.dataset.mood===state.mood);}
function readInputs(){state.count=+$('#color-count').value;state.comment=$('#request').value.trim();if(state.source==='color'){const hex=normalizeHex($('#base-hex').value);$('#base-error').hidden=!!hex;if(!hex){$('#base-hex').focus();return false;}state.base=hex;$('#base-color').value=hex;$('#base-hex').value=hex;}if(state.source==='image'&&!state.imageColors.length){toast('先に参考画像を選んでください');$('#image-input').focus();return false;}return true;}
function generate(advance=false){if(!readInputs())return;stash();if(advance)state.seed++;const result=generatePalettes({...state,referenceColors:advance&&palette()?palette().colors:[]});state.palettes=result.palettes;state.selected=0;const interpreted=result.parsed.labels.length?'反映した条件：'+result.parsed.labels.join(' ／ '):state.comment?'配色に変換できる語句がありませんでした。コメント全文はAIへの指示文に引き継ぎます。':'条件に合わせた6案です。色を固定すると次の提案にも残ります。';$('#interpretation').textContent=interpreted+(state.palettes.length<6?` 固定条件が多いため、異なる配色は${state.palettes.length}案です。`:'')+(palette().warnings.length?' '+palette().warnings.join(' '):'');render();}
function render(){renderPreview();renderActive();renderCandidates();renderExport();$('#selected-name').textContent=palette().name;$('#count-label').value=state.count+'色';$('#color-count').value=state.count;$('#undo').disabled=!state.history.length;}
function renderPreview(){
 const colors=palette().colors,p=colors[0],s=colors[1],a=colors[2]||colors[0],preview=$('#preview');preview.style.setProperty('--p',p);preview.style.setProperty('--s',s);preview.style.setProperty('--a',a);preview.style.setProperty('--pt',inkFor(p));preview.style.setProperty('--st',inkFor(s));preview.style.setProperty('--at',inkFor(a));
 $('#preview-caption').textContent={web:'WEBSITE PREVIEW',lp:'LANDING PAGE PREVIEW',illustration:'ILLUSTRATION PREVIEW'}[state.view];
 $$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===state.view));
 if(state.view==='web')preview.innerHTML=`<div class="mock-nav"><div class="mock-logo"><i></i>iroha.</div><span>ABOUT　　SERVICE　　CONTACT</span></div><div class="web-hero"><div><div class="mock-kicker">MAKE ROOM FOR WHAT YOU LOVE</div><div class="mock-title">好きなものと、<br>心地よく暮らす。</div><p class="mock-body">いつもの毎日に、あなたらしい彩りを。<br>小さな選択から、新しい暮らしがはじまります。</p><span class="mock-button">わたしたちについて　↗</span></div><div class="art-scene" aria-label="配色を適用した植物と風景"><i class="scene-stem"></i></div></div><div class="web-features"><div><b>01</b> 大切にしていること</div><div><b>02</b> つくっているもの</div><div><b>03</b> これからの暮らし</div></div>`;
 else if(state.view==='lp')preview.innerHTML=`<div class="mock-nav"><div class="mock-logo"><i></i>iroha. academy</div><span>あなたの一歩を、ここから。</span></div><div class="lp-body"><div><span class="lp-label">自分らしく、はじめよう</span><div class="mock-title">その「好き」を、<br>次の一歩に。</div><p class="mock-body">アイデアを形にする、小さなレッスン。<br>今日からできることが、きっと見つかる。</p><span class="mock-button">無料で体験する　→</span></div><div class="lp-poster"><small>THE LITTLE CREATIVE GUIDE</small><strong>つくるって、<br>おもしろい。</strong><span>IDEAS INTO EVERYDAY LIFE　↗</span></div></div><div class="lp-proof">自分のペースで学べる　／　はじめての方にも　／　実践しながら身につく</div>`;
 else preview.innerHTML=`<div class="illustration-wrap"><div class="illustration-copy"><div class="mock-kicker">A LITTLE COLOR, A NEW STORY</div><div class="mock-title">色が変わると、<br>物語も変わる。</div><p class="mock-body">同じ形、同じ構図。<br>色だけで、こんなに違う。</p><small>メイン＝山・花びん<br>サブ＝空・背景の面<br>アクセント＝太陽・花</small></div><svg class="illustration-svg" viewBox="0 0 300 300" role="img" aria-label="テーマカラーを適用した山、太陽、植物のイラスト"><defs><clipPath id="scene-clip"><rect x="8" y="5" width="284" height="285" rx="135"/></clipPath></defs><g clip-path="url(#scene-clip)"><rect x="8" y="5" width="284" height="285" fill="${s}"/><circle cx="213" cy="73" r="37" fill="${a}"/><path d="M-10 250L110 97L254 290Z" fill="${p}"/><path d="M120 290L250 142L329 275V300Z" fill="${colors[3]||a}"/><path d="M-10 263Q130 240 302 263V302H-10" fill="${colors[4]||'#FFFFFF'}"/><path d="M62 251Q87 179 64 145M75 218L44 190M75 197L107 165" fill="none" stroke="#111111" stroke-width="3"/><ellipse cx="49" cy="183" rx="12" ry="24" transform="rotate(-35 49 183)" fill="${colors[5]||a}"/><ellipse cx="104" cy="162" rx="13" ry="24" transform="rotate(35 104 162)" fill="${colors[6]||a}"/><ellipse cx="64" cy="146" rx="13" ry="23" fill="${colors[7]||s}"/><path d="M44 234H91L84 288H51Z" fill="${p}"/><path d="M214 272V221M214 246L194 232M214 237L233 218" stroke="#111111" stroke-width="3" fill="none"/><circle cx="213" cy="214" r="12" fill="${a}"/><circle cx="193" cy="228" r="9" fill="${a}"/><circle cx="235" cy="214" r="10" fill="${a}"/></g></svg></div>`;
 // Use every supplementary theme color on visible parts of Web/LP previews.
 if(state.view!=='illustration'&&colors.length>3){const ribbon=el('div','preview-extra');ribbon.style.cssText='display:flex;height:8px';colors.slice(3).forEach(c=>{let i=el('i');i.style.cssText=`flex:1;background:${c}`;ribbon.append(i)});preview.append(ribbon);}
 renderContrast();
}
function renderContrast(){const p=palette().colors[0],a=palette().colors[2]||p;const cta=state.view==='lp'?a:p;const textRatio=contrast(p,'#FFFFFF'),buttonRatio=contrast(cta,inkFor(cta));const div=$('#contrast');div.replaceChildren();const badge=el('span',buttonRatio>=4.5?'pass':'warn',`ボタン文字 ${buttonRatio.toFixed(2)}:1 ${buttonRatio>=4.5?'✓':'要調整'}`);const headline=el('span',textRatio>=4.5?'pass':'warn',`メイン色の小さい文字／白背景 ${textRatio.toFixed(2)}:1 ${textRatio>=4.5?'✓':'読みにくい組み合わせ'}`);div.append(badge,headline);if(state.view==='illustration'){badge.textContent='配色比率は目安。モチーフに合わせて調整';badge.className='';}}
function renderActive(){const colors=palette().colors,div=$('#active-colors');div.replaceChildren();div.style.setProperty('--count',colors.length);div.classList.toggle('many',colors.length>4);colors.forEach((color,i)=>{const tile=el('div','color-tile'),block=el('div','color-block');block.style.setProperty('--s',color);const picker=el('input','color-edit');picker.type='color';picker.value=color;picker.setAttribute('aria-label',ROLE_NAMES[i]+'の色を編集');picker.addEventListener('change',()=>{stash();palette().colors[i]=picker.value.toUpperCase();if(state.locks[i])state.locks[i]=palette().colors[i];palette().name='自分で調整した配色';render();});const lock=el('button','lock',state.locks[i]?'固定中':'固定');lock.setAttribute('aria-label',ROLE_NAMES[i]+'を固定');lock.setAttribute('aria-pressed',!!state.locks[i]);lock.addEventListener('click',()=>{if(state.locks[i])delete state.locks[i];else state.locks[i]=color;renderActive();});block.append(picker,lock);const hex=el('button','hex-copy',color);hex.title=color+' をコピー';hex.addEventListener('click',()=>copy(color));tile.append(block,hex,el('span','role-label',ROLE_NAMES[i]));div.append(tile);});}
function renderCandidates(){const div=$('#candidates');div.replaceChildren();state.palettes.forEach((p,i)=>{const button=el('button','candidate');button.setAttribute('aria-pressed',state.selected===i);button.setAttribute('aria-label',p.name+'、'+p.colors.join('、'));button.append(swatches(p.colors,'candidate-swatches'));const info=el('div','candidate-info');info.append(el('strong',null,p.name),el('small',null,p.description));button.append(info);button.addEventListener('click',()=>{if(state.selected===i)return;stash();state.selected=i;for(const key of Object.keys(state.locks))state.locks[key]=p.colors[key];render();});div.append(button);});}
function renderExport(){let output=state.format==='css'?exportCss(palette()):state.format==='json'?JSON.stringify(exportData(palette(),state.view,state.comment),null,2):exportPrompt(palette(),state.view,state.comment);$('#export-text').value=output;$$('[data-format]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.format===state.format));$('#copy-export').textContent={prompt:'指示文をコピー ↗',css:'CSSをコピー ↗',json:'JSONをコピー ↗'}[state.format];}
function renderFavorites(){const div=$('#favorites');div.replaceChildren();$('#favorites-section').hidden=!state.favorites.length;state.favorites.forEach((p,index)=>{const wrap=el('div','favorite-item'),load=el('button');load.title=p.name;load.setAttribute('aria-label',p.name+'を読み込む');load.append(...swatches(p.colors,'').children);load.addEventListener('click',()=>{stash();state.palettes=[{...p,colors:[...p.colors],description:'保存した配色',warnings:[]}];state.selected=0;state.count=p.colors.length;state.locks={};render();toast('保存した配色を読み込みました');});const remove=el('button',null,'×');remove.setAttribute('aria-label',p.name+'を保存から削除');remove.addEventListener('click',()=>{state.favorites.splice(index,1);persistFavorites();renderFavorites();});wrap.append(load,remove);div.append(wrap);});}
function persistFavorites(){try{localStorage.setItem('iro-atelierv1',JSON.stringify(state.favorites));return true;}catch{toast('このブラウザでは保存できません。共有リンクか配色画像をご利用ください。');return false;}}
function validSaved(p){return p&&typeof p.name==='string'&&Array.isArray(p.colors)&&p.colors.length>=2&&p.colors.length<=8&&p.colors.every(c=>normalizeHex(c));}
function setup(){
 const moods=$('#moods');MOODS.forEach(m=>{const b=el('button','mood-button');b.dataset.mood=m.id;b.setAttribute('aria-pressed',state.mood===m.id);b.append(swatches(m.colors.slice(0,3),'mini-dots'),el('span',null,m.label));b.addEventListener('click',()=>{state.mood=m.id;state.seed=0;updateMood();generate();});moods.append(b);});
 ['#52796F','#416C9B','#B4575F','#BF8861','#9275A1','#D5B65B','#414A57','#7CA8A3'].forEach(c=>{let b=el('button');b.style.setProperty('--s',c);b.title=c;b.setAttribute('aria-label',`基準色を${c}にする`);b.addEventListener('click',()=>{$('#base-color').value=c;$('#base-hex').value=c;state.base=c;state.seed=0;generate();});$('#base-presets').append(b);});
 $$('[data-source]').forEach(b=>b.addEventListener('click',()=>{setSource(b.dataset.source);if(state.source!=='image'||state.imageColors.length){state.seed=0;generate();}}));
 $('#color-count').addEventListener('input',()=>{$('#count-label').value=$('#color-count').value+'色'});$('#color-count').addEventListener('change',()=>{const n=+$('#color-count').value;for(const k of Object.keys(state.locks))if(+k>=n)delete state.locks[k];generate();});
 $('#base-color').addEventListener('input',()=>{$('#base-hex').value=$('#base-color').value.toUpperCase();$('#base-error').hidden=true;});$('#base-color').addEventListener('change',()=>{state.seed=0;generate();});$('#base-hex').addEventListener('change',()=>{state.seed=0;generate();});
 $('#request').addEventListener('input',()=>{state.comment=$('#request').value.trim();renderExport();});
 $$('[data-request]').forEach(b=>b.addEventListener('click',()=>{const t=$('#request');t.value=(t.value.trim()?t.value.trim()+'。':'')+b.dataset.request;generate(true);}));
 $('#generate').addEventListener('click',()=>generate(true));$('#more').addEventListener('click',()=>generate(true));
 $$('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;renderPreview();renderExport();}));
 $$('[data-format]').forEach(b=>b.addEventListener('click',()=>{state.format=b.dataset.format;renderExport();}));
 $('#copy-export').addEventListener('click',()=>copy($('#export-text').value));
 $('#undo').addEventListener('click',()=>{if(!state.history.length)return;Object.assign(state,JSON.parse(state.history.pop()));render();});
 $('#save-favorite').addEventListener('click',()=>{if(state.favorites.some(p=>p.colors.join()===palette().colors.join()))return toast('この配色は保存済みです');if(state.favorites.length>=12)return toast('保存は12件までです。不要な配色を削除してください。');state.favorites.push({name:palette().name,colors:[...palette().colors]});if(persistFavorites())toast('配色を保存しました');renderFavorites();});
 $('#download').addEventListener('click',downloadImage);$('#share').addEventListener('click',()=>{const url=new URL(location.href);url.hash='palette='+palette().colors.map(c=>c.slice(1)).join('-')+'&view='+state.view;copy(url.toString());});
 $('#image-input').addEventListener('change',loadImage);
 try{const saved=JSON.parse(localStorage.getItem('iro-atelierv1')||'[]');if(Array.isArray(saved))state.favorites=saved.filter(validSaved).slice(0,12).map(p=>({name:p.name.slice(0,80),colors:p.colors.map(normalizeHex)}));}catch{}
 state.palettes=generatePalettes(state).palettes;const params=new URLSearchParams(location.hash.slice(1)),shared=params.get('palette');if(shared){const colors=shared.split('-').map(x=>normalizeHex(x));if(colors.length>=2&&colors.length<=8&&colors.every(Boolean)){state.count=colors.length;state.palettes=[{name:'共有された配色',description:'共有リンクから読み込みました',colors,warnings:[]}];if(['web','lp','illustration'].includes(params.get('view')))state.view=params.get('view');toast('共有された配色を読み込みました');}else toast('共有リンクの配色を読み込めませんでした');}
 render();renderFavorites();
}
let imageJob=0;
async function loadImage(){const job=++imageJob,file=$('#image-input').files[0];if(!file)return;if(file.size>15*1024*1024){$('#image-status').textContent='15MB以下の画像を選んでください。';return;}if(!/^image\/(png|jpeg|webp|gif|avif)$/.test(file.type)){$('#image-status').textContent='PNG・JPEG・WebP・GIF・AVIFの画像を選んでください。';return;}
 $('#image-status').textContent='画像から色を抽出しています…';const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(job!==imageJob){URL.revokeObjectURL(url);return;}const canvas=document.createElement('canvas'),scale=Math.min(1,180/Math.max(img.naturalWidth,img.naturalHeight));canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,canvas.width,canvas.height);const colors=extractColors(ctx.getImageData(0,0,canvas.width,canvas.height).data);if(!colors.length)throw new Error('透明な画像からは色を抽出できません。');state.imageColors=colors;if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=url;$('#image-preview').src=url;$('#image-result').hidden=false;const div=$('#image-colors');div.replaceChildren();colors.forEach(c=>{const b=el('button');b.style.setProperty('--s',c);b.title=c;b.setAttribute('aria-label',c+'を基準色にする');b.addEventListener('click',()=>{setSource('color');$('#base-color').value=c;$('#base-hex').value=c;state.seed=0;generate();});div.append(b);});$('#image-status').textContent=`${colors.length}色を抽出しました。抽出色をもとに調和させた6案です。画像は送信していません。`;state.seed=0;generate();}catch(e){URL.revokeObjectURL(url);if(job===imageJob)$('#image-status').textContent=e.message.includes('透明')?e.message:'この画像は読み込めませんでした。別のPNGやJPEGをお試しください。';}}
function downloadImage(){const p=palette(),canvas=document.createElement('canvas');canvas.width=1440;canvas.height=760;const ctx=canvas.getContext('2d');ctx.fillStyle='#FFFFFF';ctx.fillRect(0,0,1440,760);ctx.fillStyle='#111111';ctx.font='600 30px "Noto Sans JP", sans-serif';ctx.fillText('いろのアトリエ / COLOR STUDIO',64,75);ctx.font='22px "Noto Sans JP", sans-serif';ctx.fillText(p.name,64,120);const width=1312/p.colors.length;p.colors.forEach((c,i)=>{ctx.fillStyle=c;ctx.fillRect(64+width*i,164,width,350);ctx.fillStyle='#111111';ctx.font='600 22px monospace';ctx.fillText(c,72+width*i,552);ctx.font='17px "Noto Sans JP", sans-serif';ctx.fillText(ROLE_NAMES[i],72+width*i,590);});ctx.font='19px "Noto Sans JP", sans-serif';ctx.fillText('基本色：背景 #FFFFFF / 本文・線 #111111',64,660);ctx.fillStyle='#666666';ctx.font='16px sans-serif';ctx.fillText('rental-space.net/tools/color-studio/',64,709);canvas.toBlob(blob=>{if(!blob)return toast('画像を保存できませんでした');const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='iro-palette-'+p.colors.map(c=>c.slice(1)).join('-')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('配色画像を保存しました');},'image/png');}
setup();
