function nav(){return '<div class="mock-nav"><div class="mock-logo"><i></i>iroha.</div><span>ABOUT　　SERVICE　　CONTACT</span></div>';}
function button(label){return `<span class="mock-button demo-action">${label}　→</span>`;}
function scene(){return '<div class="art-scene"><i class="scene-stem"></i></div>';}
export function previewMarkup(view,design,{poor=false}={}){
 const r=design.roles;
 if(view==='app')return `<div class="app-demo-wrap"><div class="app-demo-caption"><p class="mock-kicker">MOBILE APP / ${design.mode==='dark'?'DARK':'LIGHT'}</p><h3>迷わず使える、<br>色の役割。</h3><p>操作・選択・エラーを<br>色と文字・形で区別します。</p><div class="app-legend"><span><i style="background:${r.action}"></i>主要な操作</span><span><i style="background:${r.selectedSurface};border:1px solid ${r.selectedText}"></i>選択中</span><span><i style="background:${r.error}"></i>エラー＋説明</span></div></div><div class="phone-demo"><div class="phone-status">9:41 <span>● ▰</span></div><div class="phone-heading"><small>DAILY NOTE</small><h3>今日のやること</h3><p>少しずつ、自分のペースで。</p></div><div class="phone-card"><span class="phone-tag">今日の予定</span><strong>アイデアをひとつ書く</strong><small>まずは小さな一歩から。</small></div><div class="phone-input"><span>タイトル <small>必須</small></span><div class="demo-input">未入力</div><p class="demo-error">! タイトルを入力してください</p></div>${button('予定を追加する')}<span class="phone-secondary">キャンセル</span><div class="phone-bottom"><span class="is-selected"><b>⌂</b>ホーム<small>選択中</small></span><span><b>▤</b>一覧</span><span><b>⚙</b>設定</span></div></div></div>`;
 if(view==='lp')return `${nav()}<div class="lp-body"><div><span class="lp-label">自分らしく、はじめよう</span><div class="mock-title">その「好き」を、<br>次の一歩に。</div><p class="mock-body">アイデアを形にする、小さなレッスン。<br>今日からできることが、きっと見つかる。</p>${button('無料で体験する')}<div class="demo-secondary-link">講座の内容を見る</div></div><div class="lp-poster"><small>THE LITTLE CREATIVE GUIDE</small><strong>つくるって、<br>おもしろい。</strong><span>IDEAS INTO EVERYDAY LIFE　↗</span></div></div><div class="lp-proof">自分のペースで学べる　／　はじめての方にも　／　実践しながら身につく</div>`;
 if(view==='illustration'){
  const main=poor?r.secondary:r.subject,bg=poor?r.brand:r.sceneBackground,accent=poor?r.accent:r.focal,line=poor?main:r.sceneLine;
  const mainSize=design.strategy==='bold'?115:design.strategy==='quiet'?82:100,accentSize=design.strategy==='bold'?30:design.strategy==='quiet'?15:23;
  return `<div class="illustration-wrap"><div class="illustration-copy"><div class="mock-kicker">FOCUS / VALUE / BALANCE</div><div class="mock-title">主役が伝わる、<br>色の使い方。</div><p class="mock-body">背景・主役・アクセント。<br>明暗と面積に役割を持たせます。</p><small>グレースケールでも確認できます。<br>数値は構図を考えるための目安です。</small></div><svg class="illustration-svg" viewBox="0 0 300 300" role="img" aria-label="背景、主役の花びん、花のアクセントの配色見本"><rect width="300" height="300" rx="30" fill="${bg}"/><circle cx="230" cy="67" r="42" fill="${poor?accent:bg}"/><path d="M150 217V86M150 166L95 130M150 142L205 99" fill="none" stroke="${line}" stroke-width="4"/><ellipse cx="99" cy="136" rx="15" ry="30" transform="rotate(-40 99 136)" fill="${main}" stroke="${line}" stroke-width="2"/><ellipse cx="199" cy="106" rx="14" ry="28" transform="rotate(40 199 106)" fill="${main}" stroke="${line}" stroke-width="2"/><circle cx="150" cy="79" r="${accentSize}" fill="${accent}" stroke="${line}" stroke-width="2"/><path d="M${150-mainSize/2} 192H${150+mainSize/2}L${150+mainSize*.34} 273H${150-mainSize*.34}Z" fill="${main}" stroke="${line}" stroke-width="3"/><path d="M75 277H226" stroke="${line}" stroke-width="2"/>${poor?`<circle cx="45" cy="68" r="35" fill="${accent}"/><circle cx="255" cy="230" r="30" fill="${accent}"/>`:''}</svg></div>`;
 }
 return `${nav()}<div class="web-hero"><div><div class="mock-kicker">MAKE ROOM FOR WHAT YOU LOVE</div><div class="mock-title">好きなものと、<br>心地よく暮らす。</div><p class="mock-body">いつもの毎日に、あなたらしい彩りを。<br>小さな選択から、新しい暮らしがはじまります。</p>${button('わたしたちについて')}<div class="demo-secondary-link">サービスを見る</div></div>${scene()}</div><div class="web-features"><div><b>01</b> 大切にしていること</div><div><b>02</b> つくっているもの</div><div><b>03</b> これからの暮らし</div></div>`;
}
