import {toHex,ROLE_NAMES} from './engine.mjs?v=20260928-knowledge1';
import {isNeutral,dominantImageColors,initialMappings} from './recolor-core.mjs?v=20260928-knowledge1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
export function setupRecolor({snapshot,onChange,notify}){
 let original=null,rows=[],patches=[],region=null,worker=null,busy=false,pending=null,revision=0,loaded=0,lastKey='',timer,drag=null,custom=false,thumbs=[],thumbSize=null,filename='',lastResult=0,lastCount=0;
 const before=$('#recolor-before'),after=$('#recolor-after'),overlay=$('#recolor-region');
 function choices(design,palette){return [['keep','変更しない',null],...palette.colors.map((c,i)=>['theme:'+i,ROLE_NAMES[i],c]),...(design.view==='illustration'?[['role:sceneBackground','背景',design.roles.sceneBackground],['role:sceneLine','輪郭',design.roles.sceneLine]]:[['role:background','背景',design.roles.background],['role:text','本文',design.roles.text],['role:surface','カードの面',design.roles.surface],['role:action','主要ボタン',design.roles.action],['role:onAction','ボタン上の文字',design.roles.onAction],['role:link','リンク',design.roles.link]])];}
 function mappings(index){const s=snapshot(),opts=choices(s.designs[index],s.palettes[index]);return rows.map(r=>{const found=opts.find(x=>x[0]===r.target)||opts[0];return {from:r.from,to:found[2],role:found[1]};});}
 function localMappings(index){const s=snapshot(),opts=choices(s.designs[index],s.palettes[index]);return patches.map(p=>{const found=opts.find(x=>x[0]===p.target)||opts[0];return {from:p.from,to:found[2],role:found[1],region:p.region};});}
 function settings(){return {tolerance:+$('#recolor-tolerance').value/500,keepNeutrals:$('#recolor-neutrals').checked,preserveShading:$('#recolor-shading').checked,region};}
 function data(){if(!original||!custom)return null;const m=mappings(snapshot().selected).map(x=>settings().keepNeutrals&&isNeutral(x.from)?{...x,requestedTo:x.to,to:null,role:'白・黒・グレーを保護'}:x);return {method:'指定色と似た色の置換（物体や文字の意味は自動判別しません）',priority:'添付画像はこの変更対応を優先。一般見本の用途別役割は参考にとどめる。',width:original.width,height:original.height,sourceWidth:original.sourceWidth,sourceHeight:original.sourceHeight,mappings:m,patches:localMappings(snapshot().selected).map(p=>({...p,...(settings().keepNeutrals&&isNeutral(p.from)?{requestedTo:p.to,to:null,role:'白・黒・グレーを保護'}:{}),region:{...p.region,units:'画像全体を0〜1とした範囲'}})),patchPriority:'部分指定は全体の対応表と範囲制限より優先。重なる場合は後の指定を優先。元画像の色で照合する。白黒の保護は共通。',keepNeutrals:settings().keepNeutrals,preserveShading:settings().preserveShading,tolerance:settings().tolerance,region:region?{...region,units:'画像全体を0〜1とした範囲'}:null,scope:'取り込んだ画像のコントラストやアクセシビリティは自動検査していません。元画像と変更後のPNGも制作AIに添付してください。'};}
 function prompt(){const d=data();if(!d)return '';return '\n\n【取り込んだ画像の変更対応】\n上の用途別の色指定は一般見本です。添付画像には次の変更対応を優先し、残す色は変えないでください。\n元画像と変更後のPNGを参照し、形・文字・レイアウトを保って色を変更してください。\n'+d.mappings.map(m=>`${m.from} → ${m.to?m.to+'（'+m.role+'）':'変更しない'}`).join('\n')+`\n白・黒・グレー：${d.keepNeutrals?'そのまま残す':'対応表の指定に従う'}。陰影：${d.preserveShading?'元の明暗差をできるだけ残す':'指定色にそろえる'}。\n`+(d.region?`変更する範囲：左${(region.x*100).toFixed(1)}%、上${(region.y*100).toFixed(1)}%、幅${(region.width*100).toFixed(1)}%、高さ${(region.height*100).toFixed(1)}%。範囲外は維持。\n`:'変更する範囲：画像全体。\n')+(d.patches.length?'部分的な差し色（全体設定より優先、後の指定を優先）：\n'+d.patches.map(p=>`${p.from} → ${p.to||'変更しない'}（${p.role}）、左${(p.region.x*100).toFixed(1)}%、上${(p.region.y*100).toFixed(1)}%、幅${(p.region.width*100).toFixed(1)}%、高さ${(p.region.height*100).toFixed(1)}%`).join('\n')+'\n':'')+d.scope;}
 function selectMode(value){custom=value;$$('[data-preview-source]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.previewSource===(custom?'custom':'sample')));$('#custom-preview').hidden=!custom;$('#sample-preview').hidden=custom;$('#preview-options').hidden=custom;$('#recolor-scope-note').hidden=!(custom&&original);onChange();if(custom&&original)update();}
 function renderRows(){const s=snapshot(),opts=choices(s.designs[s.selected],s.palettes[s.selected]);$('#recolor-mappings').replaceChildren(...rows.map((r,i)=>{if(!opts.some(x=>x[0]===r.target))r.target='keep';const row=node('div');row.className='recolor-map';const source=node('span');source.className='recolor-swatch';const dot=node('i');dot.style.background=r.from;source.append(dot,node('code',r.from));const select=node('select');select.setAttribute('aria-label',r.from+' の変更先');opts.forEach(([key,label])=>{const o=node('option',label);o.value=key;select.append(o);});select.value=r.target;select.addEventListener('change',()=>{rows[i].target=select.value;rows[i].auto=false;lastKey='';update();onChange();});const target=node('span');target.className='recolor-swatch';const c=opts.find(x=>x[0]===r.target)?.[2],protectedColor=$('#recolor-neutrals').checked&&isNeutral(r.from);const dest=node('i');dest.style.background=protectedColor?r.from:c||r.from;target.append(dest,node('code',protectedColor&&c?'保護中':c||'そのまま'));row.append(source,node('span','→'),select,target);return row;}));}
 function renderAdditions(){
  const s=snapshot(),opts=choices(s.designs[s.selected],s.palettes[s.selected]).filter(x=>x[0].startsWith('theme:'));
  const target=$('#recolor-accent-target'),value=target.value;
  target.replaceChildren(...opts.map(([key,label,hex])=>{const o=node('option',label+' '+hex);o.value=key;return o;}));
  target.value=opts.some(x=>x[0]===value)?value:opts[Math.min(2,opts.length-1)][0];
  const oldPatchCount=patches.length;patches=patches.filter(p=>opts.some(x=>x[0]===p.target));if(patches.length<oldPatchCount)notify('色数を減らしたため、無くなった色の部分指定を解除しました');
  const used=new Set([...rows,...patches].filter(r=>!($('#recolor-neutrals').checked&&isNeutral(r.from))).map(r=>r.target));
  const assigned=opts.filter(x=>used.has(x[0])),unused=opts.filter(x=>!used.has(x[0]));
  $('#recolor-usage').textContent=`テーマ${opts.length}色中、${assigned.length}色を割り当て済み。`+(unused.length?' 未割当て：'+unused.map(x=>x[1]).join('・')+'。下の色を選び、変更前の画像を囲むと追加できます。':' 各色の使用面積は変更後の画像で確認してください。');
  $('#recolor-patches').replaceChildren(...patches.map((p,i)=>{const row=node('div');row.className='recolor-patch';const title=node('span',`${i+1}. ${p.from} → ${opts.find(x=>x[0]===p.target)?.[1]}（左${Math.round(p.region.x*100)}%、上${Math.round(p.region.y*100)}%）`),select=node('select');select.setAttribute('aria-label','部分指定'+(i+1)+'の色');opts.forEach(([key,label,hex])=>{const o=node('option',label+' '+hex);o.value=key;select.append(o);});select.value=p.target;select.addEventListener('change',()=>{p.target=select.value;lastKey='';update();onChange();});const remove=node('button','削除');remove.type='button';remove.addEventListener('click',()=>{patches.splice(i,1);lastKey='';update();onChange();});row.append(title,select,remove);return row;}));
 }
 function dispatch(){if(busy||!pending||!worker)return;const next=pending;pending=null;busy=true;worker.postMessage(next);}
 function schedule(){if(!original||!worker)return;const s=snapshot();const variants=s.palettes.map((_,i)=>mappings(i));const localVariants=s.palettes.map((_,i)=>localMappings(i)),opts=settings(),key=JSON.stringify([variants,localVariants,s.selected,opts]);if(key===lastKey)return;lastKey=key;const id=++revision;lastResult=0;$('#recolor-download').disabled=true;$('#recolor-status').textContent='変更後の画像を作成しています…';$('#recolor-result').setAttribute('aria-busy','true');pending={type:'render',id,variants,localVariants,selected:s.selected,options:opts};dispatch();}
 function renderThumbs(){const s=snapshot();$('#recolor-variants').replaceChildren(...s.palettes.map((p,i)=>{const b=node('button');b.className='recolor-variant';b.setAttribute('aria-pressed',i===s.selected);b.setAttribute('aria-label',p.name+'を画像で試す');const c=node('canvas');c.width=thumbSize.width;c.height=thumbSize.height;if(thumbs[i])c.getContext('2d').putImageData(new ImageData(thumbs[i],c.width,c.height),0,0);b.append(c,node('span',p.name));b.addEventListener('click',()=>{document.querySelectorAll('.candidate')[i]?.click();});return b;}));}
 function update(){if(!original)return;const count=snapshot().palettes[snapshot().selected].colors.length;if(count!==lastCount){const inferred=initialMappings(rows.map(r=>r.from),count);rows.forEach((r,i)=>{if(r.auto)r.target=inferred[i].target;});lastCount=count;}renderRows();renderAdditions();if(custom){schedule();if(thumbs.length&&lastResult===revision)renderThumbs();}}
 async function load(file){
  if(!file)return;if(!/^image\/(png|jpeg|webp|gif|avif)$/.test(file.type)){notify('PNG・JPEG・WebP・GIF・AVIFの画像を選んでください');return;}if(file.size>15*1024*1024){notify('15MB以下の画像を選んでください');return;}
  const job=++loaded,url=URL.createObjectURL(file);$('#recolor-status').textContent='元画像を読み込んでいます…';
  try{
   const img=new Image();img.src=url;await img.decode();if(job!==loaded)return;
   if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>40000000)throw new Error('画像が大きすぎます。4000万画素以下に縮小してからお試しください。');
   const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight),Math.sqrt(1500000/(img.naturalWidth*img.naturalHeight)));
   const w=Math.max(1,Math.floor(img.naturalWidth*scale)),h=Math.max(1,Math.floor(img.naturalHeight*scale));
   const working=node('canvas');working.width=w;working.height=h;const ctx=working.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,w,h);const pixels=ctx.getImageData(0,0,w,h);
   const sample=node('canvas');const k=Math.min(1,260/Math.max(w,h));sample.width=Math.max(1,Math.round(w*k));sample.height=Math.max(1,Math.round(h*k));sample.getContext('2d').imageSmoothingEnabled=false;sample.getContext('2d').drawImage(working,0,0,sample.width,sample.height);const small=sample.getContext('2d').getImageData(0,0,sample.width,sample.height);
   const colors=dominantImageColors(small.data,8);if(!colors.length)throw new Error('透明な画像には変更できる色がありません。');
   const count=snapshot().palettes[0].colors.length;rows=initialMappings(colors,count).map(r=>({...r,auto:true}));lastCount=count;patches=[];region=null;drawRegion();filename=file.name;original={width:w,height:h,sourceWidth:img.naturalWidth,sourceHeight:img.naturalHeight};thumbSize={width:sample.width,height:sample.height};thumbs=[];
   before.width=after.width=w;before.height=after.height=h;before.getContext('2d',{willReadFrequently:true}).drawImage(working,0,0);after.getContext('2d').drawImage(working,0,0);
   worker?.terminate();worker=new Worker(new URL('./recolor-worker.mjs?v=20260928-knowledge1',import.meta.url),{type:'module'});busy=false;pending=null;lastKey='';
   worker.onmessage=({data:r})=>{busy=false;if(r.id===revision){if(r.error){$('#recolor-status').textContent='画像を処理できませんでした。別の画像でお試しください。';lastKey='';}else{after.getContext('2d').putImageData(new ImageData(r.result,w,h),0,0);thumbs=r.thumbs;lastResult=r.id;$('#recolor-download').disabled=false;$('#recolor-status').textContent=r.changed?`${r.changed.toLocaleString()}画素の色を変更しました。配色や対応表を変えると更新します。`:'変更された色はありません。対応表の変更先・似た色の範囲・白黒を残す設定を確認してください。';renderThumbs();}$('#recolor-result').setAttribute('aria-busy','false');}dispatch();};
   worker.onerror=()=>{busy=false;worker?.terminate();worker=null;lastKey='';$('#recolor-status').textContent='画像処理を開始できませんでした。ページを再読み込みしてお試しください。';$('#recolor-result').setAttribute('aria-busy','false');};
   worker.postMessage({type:'init',source:{width:w,height:h,data:pixels.data},thumbnail:{width:sample.width,height:sample.height,data:small.data}},[pixels.data.buffer,small.data.buffer]);
   $('#custom-preview').classList.add('has-image');$('#recolor-drop strong').textContent='別の画像に変更する';$('#recolor-workspace').hidden=false;$('#recolor-file-info').textContent=`${file.name} ／ ${img.naturalWidth}×${img.naturalHeight}px`+(scale<1?` → プレビュー・保存は ${w}×${h}px`:'（元のサイズで保存）')+(file.type==='image/gif'?' ／ GIFは静止画として扱います':'');
   $('#recolor-scope-note').hidden=false;selectMode(true);update();onChange();
  }catch(e){if(job===loaded){$('#recolor-status').textContent=e.message.includes('画像')||e.message.includes('画素')?e.message:'画像を読み込めませんでした。別のPNGやJPEGでお試しください。';}}
  finally{URL.revokeObjectURL(url);}
 }
 function drawRegion(preview=region){overlay.hidden=!preview;if(preview){overlay.style.left=preview.x*100+'%';overlay.style.top=preview.y*100+'%';overlay.style.width=preview.width*100+'%';overlay.style.height=preview.height*100+'%';}$('#recolor-clear-region').disabled=!region;$('#recolor-region-status').textContent=region?'囲んだ範囲だけを変更':'画像全体を変更';}
 function point(e){const r=before.getBoundingClientRect();return {x:Math.max(0,Math.min(.999999,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(.999999,(e.clientY-r.top)/r.height))};}
 function rect(a,b){return {x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y)};}
 before.addEventListener('pointerdown',e=>{if(!original)return;if($('#recolor-tool').value!=='pick')e.preventDefault();before.setPointerCapture(e.pointerId);drag=point(e);});
 before.addEventListener('pointermove',e=>{if(drag&&$('#recolor-tool').value!=='pick')drawRegion(rect(drag,point(e)));});
 before.addEventListener('pointerup',e=>{if(!drag)return;const end=point(e);if($('#recolor-tool').value==='accent'){
 const r=rect(drag,end),x=Math.floor(r.x*before.width),y=Math.floor(r.y*before.height),w=Math.floor(r.width*before.width),h=Math.floor(r.height*before.height);
 if(w>=3&&h>=3){if(patches.length>=8)notify('部分指定は8箇所までです。不要な指定を削除してください。');else{
 const colors=dominantImageColors(before.getContext('2d').getImageData(x,y,w,h).data,8),from=colors.find(c=>!$('#recolor-neutrals').checked||!isNeutral(c));
 if(from){patches.push({from,target:$('#recolor-accent-target').value,region:r});lastKey='';update();onChange();notify(from+' の部分に差し色を追加しました');}else notify('白黒以外の色がある範囲を囲んでください');}}
 drawRegion();
 }else if($('#recolor-tool').value==='region'){const r=rect(drag,end);if(r.width*original.width>=3&&r.height*original.height>=3)region=r;drawRegion();lastKey='';schedule();onChange();}else if(Math.hypot(end.x-drag.x,end.y-drag.y)<.025){const d=before.getContext('2d').getImageData(Math.floor(end.x*before.width),Math.floor(end.y*before.height),1,1).data;if(d[3]){const hex=toHex(...d.slice(0,3));if(rows.some(r=>r.from===hex))notify(hex+' は対応表にあります');else if(rows.length>=12)notify('指定できる元の色は12色までです');else{rows.push({from:hex,target:'keep'});renderRows();notify(hex+' を追加しました。変更先を選んでください。');lastKey='';schedule();onChange();}}}drag=null;});
 before.addEventListener('pointercancel',()=>{drag=null;drawRegion();});
 $('#recolor-clear-region').addEventListener('click',()=>{region=null;drawRegion();lastKey='';schedule();onChange();});
 $('#recolor-tool').addEventListener('change',()=>{before.style.cursor=$('#recolor-tool').value!=='pick'?'crosshair':'copy';before.style.touchAction=$('#recolor-tool').value!=='pick'?'none':'pan-y';});
 $('#recolor-add-accent').addEventListener('click',()=>{$('#recolor-tool').value='accent';$('#recolor-tool').dispatchEvent(new Event('change'));before.scrollIntoView({behavior:'smooth',block:'center'});notify('変更前の画像で、色を分けたい範囲をドラッグして囲んでください');});
 $('#recolor-file').addEventListener('change',()=>{load($('#recolor-file').files[0]);$('#recolor-file').value='';});
 const zone=$('#recolor-drop');zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('is-dragging');});zone.addEventListener('dragleave',()=>zone.classList.remove('is-dragging'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('is-dragging');load(e.dataTransfer.files[0]);});
 $$('[data-preview-source]').forEach(b=>b.addEventListener('click',()=>selectMode(b.dataset.previewSource==='custom')));
 for(const id of ['recolor-neutrals','recolor-shading'])$('#'+id).addEventListener('change',()=>{lastKey='';update();onChange();});
 $('#recolor-tolerance').addEventListener('input',()=>{$('#recolor-tolerance-value').value=$('#recolor-tolerance').value;clearTimeout(timer);timer=setTimeout(()=>{lastKey='';schedule();onChange();},150);});
 $('#recolor-remove').addEventListener('click',()=>{loaded++;revision++;worker?.terminate();worker=null;busy=false;pending=null;original=null;rows=[];patches=[];region=null;thumbs=[];lastKey='';before.width=after.width=1;$('#custom-preview').classList.remove('has-image');$('#recolor-drop strong').textContent='色を変えたい画像を入れる';$('#recolor-workspace').hidden=true;$('#recolor-file-info').textContent='';$('#recolor-status').textContent='画像はこの端末内で処理します。サーバーには送信しません。';$('#recolor-scope-note').hidden=true;onChange();});
 $('#recolor-download').addEventListener('click',()=>{if(lastResult!==revision)return;after.toBlob(blob=>{if(!blob)return notify('保存できませんでした');const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='recolored-'+filename.replace(/\.[^.]+$/,'').slice(0,60)+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);},'image/png');});
 return {update,load,data,prompt};
}
